### PR TITLE
Fix the PSBT JSON serialization, using serde-derive

### PR DESCRIPTION
**Pull request by stevenroose**
This re-introduces serde-derive, but adds version pinning instructions to the README.

I hope that's fine. I failed to add hex support for the values of maps (like `partial_sigs: BTreeMap<PublicKey, Vec<u8>>`). For that I fear we'd need some helper crate like `serde_with`. Even though, I'm sure in theory it's possible to do manually, but I couldn't figure it out.

### CODE REVIEW

**Review by dr-orlovsky — DISMISSED** [review]
This looks good since gets rid of a lot of serde impl macros! utACK

File: src/util/psbt/mod.rs [hunk 1]
```diff
@@ -313,6 +313,88 @@ mod tests {
...
+		let keypaths: BTreeMap<PublicKey, KeySource> = vec![(
+			"0339880dc92394b7355e3d0439fa283c31de7590812ea011c4245c0674a685e883".parse().unwrap(),
+            key_source.clone(),
+		)].into_iter().collect();
+
+        let psbt = PartiallySignedTransaction {
+            global: Global {
+                version: 0,
+                xpub: {
+                    let xpub: bip32::ExtendedPubKey =
```
Comment (apoelstra) [inline src/util/psbt/mod.rs:356]: trailing whitespace here

Comment (apoelstra) [reply src/util/psbt/mod.rs:356]: This line also doesn't compile for me
```
cargo +stable  test   '--features=rand use-serde base64'       # 2020-12-21T16:02:46 / cargo 1.48.0 (65cbdd2dc 2020-10-14)
Command failed: cargo +stable test --features=rand use-serde base64
   Compiling serde_json v1.0.44
   Compiling serde_test v1.0.118
   Compiling bitcoin v0.25.2 (/tmp/tmpwjnlqhmp)
error[E0433]: failed to resolve: use of undeclared crate or module `bip32`
   --> src/util/psbt/mod.rs:356:31
    |
356 |                     let xpub: bip32::ExtendedPubKey = 
    |                               ^^^^^ use of undeclared crate or module `bip32`

error: aborting due to previous error
```

File: src/serde_utils.rs [hunk 2]
```diff
@@ -0,0 +1,107 @@
...
+        T: serde::Serialize + ::std::hash::Hash + Eq + Ord,
+        U: serde::Serialize,
+    {
+        use serde::ser::SerializeSeq;
+
+        let mut seq = s.serialize_seq(Some(v.len()))?;
+        for pair in v.iter() {
+            seq.serialize_element(&pair)?;
+        }
+        seq.end()
```
Comment (sgeisler) [inline src/serde_utils.rs:26]: What's the reason for serializing a sequence of pairs instead of using the map interfaces?

File: README.md [hunk 3]
```diff
@@ -59,6 +59,13 @@ compile with 1.29.0 you will need to run the following version-pinning command:
 cargo update -p cc --precise "1.0.41" --verbose
 ```
 
+In order to use the `use-serde` feature or to build the unit tests with 1.29.0,
+the following version-pinning commands are also needed:
+```
+cargo update --package "serde" --precise "1.0.98"
```
Comment (apoelstra) [inline README.md:65]: I don't think there's any reason to downgrade serde. I am testing on 1.29 fine without it.

File: src/serde_utils.rs (hunk 2 above)
Comment (stevenroose) [reply src/serde_utils.rs:26]: Hmm, this was just taken as is from another impl (either from the macro or from one I have in another crate). I didn't know there was an API for maps. Let me look into those.

Comment (stevenroose) [reply src/serde_utils.rs:26]: Oh.. The entire point of that module is to not use the map impl because JSON only supports that when the keys are strings and we don't want to have to use to_string and allocate strings. Let me see if there's a way to do this using serde right now. (Since I already have this attempted.) I think what we're missing is some way to hand serde the object not as a serializable but explicitly saying it must become a string or something (like what serialize_str does with types that have Display). It might be missing that one on the Map serializers.

File: README.md (hunk 3 above)
Comment (stevenroose) [reply README.md:65]: If I drop that line, I get this:
```
error: no matching version `= 1.0.118` found for package `serde_derive`
location searched: registry `https://github.com/rust-lang/crates.io-index`
versions found: 1.0.98
required by package `serde v1.0.118`
    ... which is depended on by `bitcoin v0.25.2 (file:///home/steven/code/rust/bitcoin)`
```

Because a higher serde will require a higher serde_derive. Somehow Cargo is not very smart about all that and it can't realize that it has a pin on _derive and then look for a matching serde.

Comment (stevenroose) [reply README.md:65]: The script I use is
```
set -e

MSRV="1.29.0"

CMD="rustup run ${MSRV}"

rm -f Cargo.lock
$CMD cargo generate-lockfile
$CMD cargo update --package "cc" --precise "1.0.41"
$CMD cargo update --package "serde" --precise "1.0.98"
$CMD cargo update --package "serde_derive" --precise "1.0.98"

$CMD cargo test --features "use-serde rand base64"
```

Perhaps we should commit that.

File: src/serde_utils.rs (hunk 2 above)
Comment (stevenroose) [reply src/serde_utils.rs:26]: So yeah the whole point of this module is to work around the fact that serde_json needs keys to be strings and we don't want to allocate strings for all keys.

Comment (stevenroose) [reply src/serde_utils.rs:26]: And the effective overhead is two characters per map entry, so that's quite fine. I think that's better than one allocation per map entry.

But if you want to give it a shot and try to work with the API to have serde_json accept the map keys, here is what you'd start with:
```diff
diff --cc src/serde_utils.rs
index 0c0b243,0c0b243..debc771
--- a/src/serde_utils.rs
+++ b/src/serde_utils.rs
@@@ -17,13 -17,13 +17,13 @@@ pub mod btreemap 
          T: serde::Serialize + ::std::hash::Hash + Eq + Ord,
          U: serde::Serialize,
      {
--        use serde::ser::SerializeSeq;
++        use serde::ser::SerializeMap;
  
--        let mut seq = s.serialize_seq(Some(v.len()))?;
--        for pair in v.iter() {
--            seq.serialize_element(&pair)?;
++        let mut map = s.serialize_map(Some(v.len()))?;
++        for (key, value) in v.iter() {
++            map.serialize_entry(key, value)?;
          }
--        seq.end()
++        map.end()
      }
  
      pub fn deserialize<'de, D, T, U>(d: D)
@@@ -42,14 -42,14 +42,14 @@@
              type Value = BTreeMap<T, U>;
  
              fn expecting(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
--                write!(f, "a sequence of pairs")
++                write!(f, "a map with string keys")
              }
  
--            fn visit_seq<A: serde::de::SeqAccess<'de>>(self, mut a: A)
++            fn visit_map<A: serde::de::MapAccess<'de>>(self, mut a: A)
                  -> Result<Self::Value, A::Error>
              {
                  let mut ret = BTreeMap::new();
--                while let Some((key, value)) = a.next_element()? {
++                while let Some((key, value)) = a.next_entry()? {
                      ret.insert(key, value);
                  }
                  Ok(ret)
```

Comment (sgeisler) [reply src/serde_utils.rs:26]: Ah, I see, the key probably couldn't be an object.

File: src/serde_utils.rs [hunk 4]
```diff
@@ -0,0 +1,107 @@
...
+        -> Result<S::Ok, S::Error> where
+        S: serde::Serializer,
+        T: serde::Serialize + ::std::hash::Hash + Eq + Ord,
+        U: serde::Serialize,
+    {
+        use serde::ser::SerializeSeq;
+
+        let mut seq = s.serialize_seq(Some(v.len()))?;
+        for pair in v.iter() {
+            seq.serialize_element(&pair)?;
```
Comment (sgeisler) [inline src/serde_utils.rs:24]: One slightly annoying consequence of directly serializing the tuple instead of a wrapper is that the value is serialized as array of `u8`s instead of hex like everything else.

File: README.md (hunk 3 above)
Comment (apoelstra) [reply README.md:65]: None of my scripts pin `serde` and everything works fine for me.

Comment (apoelstra) [reply README.md:65]: Oh, I'm lying, it's just that my scripts never made any progress on this PR because of the other compilation issue.

File: src/serde_utils.rs (hunk 4 above)
Comment (apoelstra) [reply src/serde_utils.rs:24]: I think this is more than slightly annoying but it's also really unclear how to fix it.

Comment (apoelstra) [reply src/serde_utils.rs:24]: It might be worthwhile to duplicate this entire module, changing `U` to `Vec<u8>` and doing hex-serialization.

Comment (sgeisler) [reply src/serde_utils.rs:24]: Could we get away with having a `Preferred(De)Serialize` trait which is identical to the `(De)Serialize` traits and has a default impl just passing through to the serde version. But for certain types we can implement default (de)serialization methods.

**Comment by stevenroose** [comment]
Pushed a few more changes:

- only do the special treatment for human-readable serializers (JSON)
- add special module for `BTreeMap<K, Vec<u8>>` where the K **is** serialized as a string and the value is hex
- add special module for `BTreeMap<K, Vec<u8>>` where the K **is NOT** serialized as a string and the value is hex

File: README.md (hunk 3 above)
Comment (elichai) [reply README.md:65]: I just tried and this worked:
`rm -rf target/ && rm Cargo.lock && cargo +1.29.0 test`

Comment (apoelstra) [reply README.md:65]: @elichai you have to add `--features=use-serde` to see the failure

File: src/util/psbt/mod.rs [hunk 5]
```diff
@@ -405,6 +410,7 @@ mod tests {
             }],
         };
         let encoded = ::serde_json::to_string(&psbt).unwrap();
+        println!("encoded PSBT: {}", encoded);
```
Comment (apoelstra) [inline src/util/psbt/mod.rs:413]: debug printf

Comment (stevenroose) [reply src/util/psbt/mod.rs:413]: Is that a problem? It's in a unit test, so it will only be printed when used with `--nocapture`. I can remove it if it's a problem. When changing any of the PSBT fields, this helps looking at how the JSON actually looks.

Comment (stevenroose) [reply src/util/psbt/mod.rs:413]: (F.e. the `Transactioin.witness` field still is `Vec<Vec<u8>>` which doesn't print as hex. I tried fixing that too, but I got tired of fighting serde for a while, might do that in another PR.)

Comment (apoelstra) [reply src/util/psbt/mod.rs:413]: Yeah, that's fair, you can leave it in.

**Review by apoelstra — APPROVED** [review]
ack 3fd94ef8570374d7f2734d83bb9b65b9771ee32d

**Review by sgeisler — APPROVED** [review]
utACK 3fd94ef8570374d7f2734d83bb9b65b9771ee32d
