### PR TITLE
Remove calls to debug_assert

### PR DESCRIPTION
**Pull request by tcharding**
Done after reading discussion on #853.

Audit the code for calls to the various `debug_assert` macros. Check if the call is likely to be add any performance costs and if not use the equivalent `assert` macro.

Done as separate patches so that each change can be fully described by the commit message.

With this PR applied there is one instance of `debug_assert!` left, the call checks against the result of `tweak_add_check`. I do not know if this call is fast or slow so I left it as it is.

### CODE REVIEW

File: src/consensus/encode.rs [hunk 1]
```diff
@@ -240,7 +240,6 @@ macro_rules! decoder_fn {
     ($name:ident, $val_type:ty, $readfn:ident, $byte_len: expr) => {
         #[inline]
         fn $name(&mut self) -> Result<$val_type, Error> {
-            debug_assert_eq!(::core::mem::size_of::<$val_type>(), $byte_len); // size_of isn't a constfn in 1.22
```
Comment (elichai) [inline src/consensus/encode.rs:243]: Why remove this?
Also, I'm pretty sure after the MSRV bump we can make this a compile-time check:
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=44cce9ee0d3113cdaaaf7c6f421d5699

File: src/util/endian.rs [hunk 2]
```diff
@@ -28,7 +28,6 @@ macro_rules! define_be_to_array {
     ($name: ident, $type: ty, $byte_len: expr) => {
         #[inline]
         pub fn $name(val: $type) -> [u8; $byte_len] {
-            debug_assert_eq!(::core::mem::size_of::<$type>(), $byte_len); // size_of isn't a constfn in 1.22
```
Comment (elichai) [inline src/util/endian.rs:31]: Same here as above

File: src/util/endian.rs [hunk 3]
```diff
@@ -41,7 +40,6 @@ macro_rules! define_le_to_array {
...
```
Comment (elichai) [inline src/util/endian.rs:44]: Same here

**Review by apoelstra — DISMISSED** [review]
ACK e2fff701f3d30a5f9f281b03d170113f61b68609

I also don't see the value in removing the size checks, but OTOH I don't see a lot of value in keeping them.

File: src/consensus/encode.rs (hunk 1 above)
Comment (tcharding) [reply src/consensus/encode.rs:243]: Cool. I'm no macro expert but is this as good or am I missing something?
```
macro_rules! const_assert {
    ($x:expr) => {
        const _UNUSED: [(); 0 - !$x as usize] = [];
    };
}
```
This works with Rust 1.29 as well.

Comment (elichai) [reply src/consensus/encode.rs:243]: OoO I didn't think that this can be done in 1.29! 
That will work but will limit the macro to work only once in every scope, otherwise, you'll get multiple definitions of `_UNUSED`. but it doesn't seem like we ever const-assert more than one thing in the same scope

**Review by TheBlueMatt — COMMENTED** [review]
At the risk of being a dick for jumping in late, I'm not sure why we'd want this - I don't have a deep understanding of PSBT, but do we really want to panic (and likely crash the user application) if we end up accidentally serializing a PSBT slightly wrong? I view these kinds of debug assertions as test cases that are slipped into the main code body because its easier to put tests there sometimes. At least on the LDK end, our stance is "panic if we're gonna lose money, return error or continue awkwardly otherwise".

**Comment by tcharding** [comment]
hmm, maybe an implicit benefit of using `assert!` over `debug_assert` is it forces devs to think 'do we _really_ need this assertion' instead of, as @TheBlueMatt says, treating the statement like a test. I would argue that the `debug_assert` -> `assert` changes in this PR are a step forward and we should still, but later, decide if these `assert` statements should exist at all.

File: src/consensus/encode.rs (hunk 1 above)
Comment (tcharding) [reply src/consensus/encode.rs:243]: Just to double check, is the simplification of the original 
```rust
[(); 0 - !{ const ASSERT: bool = $x; ASSERT } as usize] = []
``` 
to
```rust
[(); 0 - !$x as usize] = []
```
ok? I'm going to force push this change but wanted to explicitly double check with you. Thanks

**Comment by tcharding** [comment]
Changes in force push: Use @elichai's `const_assert` macro idea in the first patch. Remaining patches unchanged. Please await a response from @TheBlueMatt before considering this mergable.

**Comment by TheBlueMatt** [comment]
> hmm, maybe an implicit benefit of using assert! over debug_assert is it forces devs to think 'do we really need this assertion' instead of, as @TheBlueMatt says, treating the statement like a test.

Yea, totally fair. Sometimes it is just easier to write a test by slipping a debug assertion into the code right where you need to check something, though, though maybe such changes are better in `#[cfg(fuzzing)]` rather than debug assertions.

> I would argue that the debug_assert -> assert changes in this PR are a step forward and we should still, but later, decide if these assert statements should exist at all.

Yea, fair, no opinion on these specific assertions, I'm not super in depth on the PSBT part of the codebase so don't really have an opinion.

**Review by apoelstra — APPROVED** [review]
ACK dc97d372a0c9cecda5e259349c52acf1aae194be

By the way I think `const_assert` could be used repeatedly in the same scope if you added an extra scope inside the macro.

**Review by sanket1729 — APPROVED** [review]
utACK dc97d372a0c9cecda5e259349c52acf1aae194be

**Comment by sanket1729** [comment]
> I don't have a deep understanding of PSBT, but do we really want to panic (and likely crash the user application) if we end up accidentally serializing a PSBT slightly wrong? 

This PR is not dealing with any Psbt code.

**Comment by tcharding** [comment]
> By the way I think const_assert could be used repeatedly in the same scope if you added an extra scope inside the macro.

Nice one!

Changes in force push are to the first patch, added additional scope as suggested. No other changes.

File: src/consensus/encode.rs [hunk 4]
```diff
@@ -140,7 +140,7 @@ impl From<psbt::Error> for Error {
 pub fn serialize<T: Encodable + ?Sized>(data: &T) -> Vec<u8> {
     let mut encoder = Vec::new();
     let len = data.consensus_encode(&mut encoder).expect("in-memory writers don't error");
-    debug_assert_eq!(len, encoder.len());
+    assert_eq!(len, encoder.len());
```
Comment (Kixunil) [inline src/consensus/encode.rs:143]: Opinion: `debug_assert_eq` was fine here.

File: src/network/message.rs [hunk 5]
```diff
@@ -78,7 +78,7 @@ impl Encodable for CommandString {
     fn consensus_encode<S: io::Write>(&self, s: S) -> Result<usize, io::Error> {
         let mut rawbytes = [0u8; 12];
         let strbytes = self.0.as_bytes();
-        debug_assert!(strbytes.len() <= 12);
+        assert!(strbytes.len() <= 12);
         rawbytes[..strbytes.len()].copy_from_slice(strbytes);
```
Comment (Kixunil) [inline src/network/message.rs:82]: Slicing already performs this check. `assert` would've been better if the resulting error message was clearer than the default which I don't think is the case here. AFAIR out-of-bounds slicing prints the lengths while `assert`-ing like this doesn't. Thus this assert only has disadvantages and it's best to remove it completely.
(Side note: an assert like this could have been good before a loop.)

OT: maybe we could serialize the slice directly and fill in extra zeroes to avoid a bunch of copies. Something for opt nerds. :)

File: src/util/taproot.rs [hunk 6]
```diff
@@ -429,7 +429,7 @@ impl TaprootBuilder {
         }
         // Every iteration of the loop reduces the node_weights.len() by exactly 1
         // Therefore, the loop will eventually terminate with exactly 1 element
-        debug_assert_eq!(node_weights.len(), 1);
+        assert_eq!(node_weights.len(), 1);
```
Comment (Kixunil) [inline src/util/taproot.rs:432]: Opinion: debug was fine here.

**Review by Kixunil — COMMENTED** [review]
Firstly, changing asserts to const is great!

Personal opinion follows: If an assert guards the inputs to the function (prevents invariants breaking) which can not be or would be to cumbersome to be implemented using newtypes it has to be non-debug `assert!`. All else can be `debug_` just fine. However if people like non-debug asserts since they are cheap, I'm not going to block it.

I prefer to remove the redundant one.

File: src/consensus/encode.rs (hunk 1 above)
Comment (elichai) [reply src/consensus/encode.rs:243]: Yes :)

**Comment by elichai** [comment]
> ACK [dc97d37](https://github.com/rust-bitcoin/rust-bitcoin/commit/dc97d372a0c9cecda5e259349c52acf1aae194be)
> 
> By the way I think `const_assert` could be used repeatedly in the same scope if you added an extra scope inside the macro.

That's cool, the downside of that though is that it can't be used out of scope :) (outside of a function)

**Review by sanket1729 — APPROVED** [review]
ACk 7acaa4bf042c38c9a97a073e5849eef34fab9a6d. I can see arguments for both `debug_assert` and `assert`, but I think we all agree that for this PR it is an improvement?.

**Review by apoelstra — DISMISSED** [review]
ACK 7acaa4bf042c38c9a97a073e5849eef34fab9a6d

But sounds like there are still some open issues?

File: src/network/message.rs (hunk 5 above)
Comment (tcharding) [reply src/network/message.rs:82]: Will revisit this one after other discussion no the PR resolves. Thanks.

**Comment by tcharding** [comment]
Changing to draft, this was only meant to be a quick thing and as it has uncovered a can of worms I'll put it on the back burner till after the MSRV chaos is over.

**Comment by apoelstra** [comment]
@TheBlueMatt if these ever trigger then we (the developers) have gotten very confused about what state the library is in. I don't expect that they will ever trigger.

You are correct that these are essentially unit tests, and maybe shouldn't be inline in the code (though they are easier to find and understand this way), which is why they were originally `debug_assert`s. I also don't really understand the principle behind turning them into real asserts, but I think it's totally harmless (i.e. will not hurt perf and will not cause crashes).

**Review by apoelstra — APPROVED** [review]
ACK 15d380012b9c19dadb4dba0e408fbdef5dd39d6d

but still looks like there is disagreement about whether we want this PR

**Comment by tcharding** [comment]
Closing this since it is contentious.

**Comment by Kixunil** [comment]
Perhaps reconsider doing const asserts only, I think they'd be non-contentious. (At least I think it'd be great and never heard anyone arguing against them.)

**Comment by tcharding** [comment]
Done: https://github.com/rust-bitcoin/rust-bitcoin/pull/1000

PR 1000, BOOM!
