### PR TITLE
Change Cargo.toml serde dev deps

### PR DESCRIPTION
**Pull request by JeremyRubin**
The serde dev dependency pinning breaks compilation on my machine with various build errors, setting the version to "1" fixes the incompatibilities.

### CODE REVIEW

**Comment by dpc** [comment]
I doubt this is going to fly. AFAIR, these versions were pinned because newer version don't compile on minimum rust compiler version this project supports.

**Comment by JeremyRubin** [comment]
Is there a maximum supported version as well? As I'm presently unable to compile on latest stable, hence this patch.

**Comment by stevenroose** [comment]
Perhaps since we bumped our MSRV, we can slightly bump those as well. If only there was a table that detailed rustc compatibility for various versions of Rust crates..

**Comment by stevenroose** [comment]
I can still build with latest stable, though (1.47.0).

**Comment by stevenroose** [comment]
I played around a bit. I can remove the `serde_derive` line and still build fresh with Rust 1.29. But somehow I also don't need to pin the cc version anymore, so I'm a bit skeptical towards cargo somehow keeping more state than `Cargo.lock`? I did a `cargo clean` too..

**Comment by dr-orlovsky** [comment]
I do constantly builds for rust-bitcoin with stable and nightly, no problems ever encountered. Probably Cargo.lock issue

**Comment by apoelstra** [comment]
To continue the pile-on, I'm really surprised that you've managed to encounter any issues with dev-dependencies.

**Comment by JeremyRubin** [comment]
hmm so it turn out the issue shows up if you add the line "schemars = { version = "0.8.0", optional = true }" and no other changes, and it's limited to src/util/amount.rs.

The error is:

```
   Compiling num-traits v0.2.12
   Compiling num-traits v0.1.43
   Compiling serde_json v0.9.10
   Compiling bitcoin v0.25.0 (/home/jr/develop/judica/rust-bitcoin)
error[E0433]: failed to resolve: could not find `SeqVisitor` in `de`
    --> src/util/amount.rs:1282:29
     |
1282 |         #[derive(Serialize, Deserialize, PartialEq, Debug)]
     |                             ^^^^^^^^^^^ could not find `SeqVisitor` in `de`
     |
     = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0433]: failed to resolve: could not find `MapVisitor` in `de`
    --> src/util/amount.rs:1282:29
     |
1282 |         #[derive(Serialize, Deserialize, PartialEq, Debug)]
     |                             ^^^^^^^^^^^ could not find `MapVisitor` in `de`
     |
     = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0433]: failed to resolve: could not find `SeqVisitor` in `de`
    --> src/util/amount.rs:1314:29
     |
1314 |         #[derive(Serialize, Deserialize, PartialEq, Debug)]
     |                             ^^^^^^^^^^^ could not find `SeqVisitor` in `de`
     |
     = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0433]: failed to resolve: could not find `MapVisitor` in `de`
    --> src/util/amount.rs:1314:29
     |
1314 |         #[derive(Serialize, Deserialize, PartialEq, Debug)]
     |                             ^^^^^^^^^^^ could not find `MapVisitor` in `de`
     |
     = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0433]: failed to resolve: could not find `SeqVisitor` in `de`
    --> src/util/amount.rs:1348:29
     |
1348 |         #[derive(Serialize, Deserialize, PartialEq, Debug)]
     |                             ^^^^^^^^^^^ could not find `SeqVisitor` in `de`
     |
     = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0433]: failed to resolve: could not find `MapVisitor` in `de`
    --> src/util/amount.rs:1348:29
     |
1348 |         #[derive(Serialize, Deserialize, PartialEq, Debug)]
     |                             ^^^^^^^^^^^ could not find `MapVisitor` in `de`
     |
     = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0405]: cannot find trait `SeqVisitor` in module `_serde::de`
    --> src/util/amount.rs:1282:29
     |
1282 |         #[derive(Serialize, Deserialize, PartialEq, Debug)]
     |                             ^^^^^^^^^^^ help: a trait with a similar name exists: `Visitor`
     | 
    ::: /home/jr/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.116/src/de/mod.rs:1263:1
     |
1263 | pub trait Visitor<'de>: Sized {
     | ----------------------------- similarly named trait `Visitor` defined here
     |
     = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0405]: cannot find trait `MapVisitor` in module `_serde::de`
    --> src/util/amount.rs:1282:29
     |
1282 |         #[derive(Serialize, Deserialize, PartialEq, Debug)]
     |                             ^^^^^^^^^^^ help: a trait with a similar name exists: `Visitor`
     | 
    ::: /home/jr/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.116/src/de/mod.rs:1263:1
     |
1263 | pub trait Visitor<'de>: Sized {
     | ----------------------------- similarly named trait `Visitor` defined here
     |
     = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0412]: cannot find type `IgnoredAny` in `_serde::de::impls`
    --> src/util/amount.rs:1282:29
     |
1282 |         #[derive(Serialize, Deserialize, PartialEq, Debug)]
     |                             ^^^^^^^^^^^ not found in `_serde::de::impls`
     |
     = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider importing this struct
     |
1000 |     use serde::de::IgnoredAny;
     |

error[E0405]: cannot find trait `SeqVisitor` in module `_serde::de`
    --> src/util/amount.rs:1314:29
     |
1314 |         #[derive(Serialize, Deserialize, PartialEq, Debug)]
     |                             ^^^^^^^^^^^ help: a trait with a similar name exists: `Visitor`
     | 
    ::: /home/jr/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.116/src/de/mod.rs:1263:1
     |
1263 | pub trait Visitor<'de>: Sized {
     | ----------------------------- similarly named trait `Visitor` defined here
     |
     = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0405]: cannot find trait `MapVisitor` in module `_serde::de`
    --> src/util/amount.rs:1314:29
     |
1314 |         #[derive(Serialize, Deserialize, PartialEq, Debug)]
     |                             ^^^^^^^^^^^ help: a trait with a similar name exists: `Visitor`
     | 
    ::: /home/jr/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.116/src/de/mod.rs:1263:1
     |
1263 | pub trait Visitor<'de>: Sized {
     | ----------------------------- similarly named trait `Visitor` defined here
     |
     = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0412]: cannot find type `IgnoredAny` in `_serde::de::impls`
    --> src/util/amount.rs:1314:29
     |
1314 |         #[derive(Serialize, Deserialize, PartialEq, Debug)]
     |                             ^^^^^^^^^^^ not found in `_serde::de::impls`
     |
     = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider importing this struct
     |
1000 |     use serde::de::IgnoredAny;
     |

error[E0405]: cannot find trait `SeqVisitor` in module `_serde::de`
    --> src/util/amount.rs:1348:29
     |
1348 |         #[derive(Serialize, Deserialize, PartialEq, Debug)]
     |                             ^^^^^^^^^^^ help: a trait with a similar name exists: `Visitor`
     | 
    ::: /home/jr/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.116/src/de/mod.rs:1263:1
     |
1263 | pub trait Visitor<'de>: Sized {
     | ----------------------------- similarly named trait `Visitor` defined here
     |
     = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0405]: cannot find trait `MapVisitor` in module `_serde::de`
    --> src/util/amount.rs:1348:29
     |
1348 |         #[derive(Serialize, Deserialize, PartialEq, Debug)]
     |                             ^^^^^^^^^^^ help: a trait with a similar name exists: `Visitor`
     | 
    ::: /home/jr/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.116/src/de/mod.rs:1263:1
     |
1263 | pub trait Visitor<'de>: Sized {
     | ----------------------------- similarly named trait `Visitor` defined here
     |
     = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0412]: cannot find type `IgnoredAny` in `_serde::de::impls`
    --> src/util/amount.rs:1348:29
     |
1348 |         #[derive(Serialize, Deserialize, PartialEq, Debug)]
     |                             ^^^^^^^^^^^ not found in `_serde::de::impls`
     |
     = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider importing this struct
     |
1000 |     use serde::de::IgnoredAny;
     |

error[E0603]: module `impls` is private
    --> src/util/amount.rs:1282:29
     |
1282 |         #[derive(Serialize, Deserialize, PartialEq, Debug)]
     |                             ^^^^^^^^^^^ private module
     |
note: the module `impls` is defined here
    --> /home/jr/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.116/src/de/mod.rs:123:1
     |
123  | mod impls;
     | ^^^^^^^^^^

error[E0603]: module `impls` is private
    --> src/util/amount.rs:1314:29
     |
1314 |         #[derive(Serialize, Deserialize, PartialEq, Debug)]
     |                             ^^^^^^^^^^^ private module
     |
note: the module `impls` is defined here
    --> /home/jr/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.116/src/de/mod.rs:123:1
     |
123  | mod impls;
     | ^^^^^^^^^^

error[E0603]: module `impls` is private
    --> src/util/amount.rs:1348:29
     |
1348 |         #[derive(Serialize, Deserialize, PartialEq, Debug)]
     |                             ^^^^^^^^^^^ private module
     |
note: the module `impls` is defined here
    --> /home/jr/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.116/src/de/mod.rs:123:1
     |
123  | mod impls;
     | ^^^^^^^^^^

error[E0726]: implicit elided lifetime not allowed here
    --> src/util/amount.rs:1282:29
     |
1282 |         #[derive(Serialize, Deserialize, PartialEq, Debug)]
     |                             ^^^^^^^^^^^- help: indicate the anonymous lifetime: `<'_>`
     |
     = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0726]: implicit elided lifetime not allowed here
    --> src/util/amount.rs:1314:29
     |
1314 |         #[derive(Serialize, Deserialize, PartialEq, Debug)]
     |                             ^^^^^^^^^^^- help: indicate the anonymous lifetime: `<'_>`
     |
     = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0726]: implicit elided lifetime not allowed here
    --> src/util/amount.rs:1348:29
     |
1348 |         #[derive(Serialize, Deserialize, PartialEq, Debug)]
     |                             ^^^^^^^^^^^- help: indicate the anonymous lifetime: `<'_>`
     |
     = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0106]: missing lifetime specifier
    --> src/util/amount.rs:1282:29
     |
1282 |         #[derive(Serialize, Deserialize, PartialEq, Debug)]
     |                             ^^^^^^^^^^^ expected named lifetime parameter
     |
     = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider introducing a named lifetime parameter
     |
1282 |         #[derive(Serialize, 'a, Deserialize<'a>, PartialEq, Debug)]
     |                             ^^^^^^^^^^^^^^^

error[E0106]: missing lifetime specifier
    --> src/util/amount.rs:1314:29
     |
1314 |         #[derive(Serialize, Deserialize, PartialEq, Debug)]
     |                             ^^^^^^^^^^^ expected named lifetime parameter
     |
     = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider introducing a named lifetime parameter
     |
1314 |         #[derive(Serialize, 'a, Deserialize<'a>, PartialEq, Debug)]
     |                             ^^^^^^^^^^^^^^^

error[E0106]: missing lifetime specifier
    --> src/util/amount.rs:1348:29
     |
1348 |         #[derive(Serialize, Deserialize, PartialEq, Debug)]
     |                             ^^^^^^^^^^^ expected named lifetime parameter
     |
     = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider introducing a named lifetime parameter
     |
1348 |         #[derive(Serialize, 'a, Deserialize<'a>, PartialEq, Debug)]
     |                             ^^^^^^^^^^^^^^^

error: aborting due to 24 previous errors

Some errors have detailed explanations: E0106, E0405, E0412, E0433, E0603.
For more information about an error, try `rustc --explain E0106`.
error: could not compile `bitcoin`

To learn more, run the command again with --verbose.
```

**Comment by JeremyRubin** [comment]
Cargo.lock does have something to do with it, clearing it does help.

I can trigger the issue by adding the line "schemars = { version = "0.8.0", optional = true }" and no other changes, and it's limited to src/util/amount.rs.

This lead me to observing that the issue is because somehow adding optional schemars makes cargo pull in serde_dervie and serde_json 0.9.*. I can fix the issue by pinning >= 1.0.0

```
serde_derive = "<1.0.99, >=1.0.0"
serde_json = "<1.0.45, >=1.0.0"
```

**Comment by JeremyRubin** [comment]
some discussion on https://github.com/rust-bitcoin/rust-bitcoin/pull/501#pullrequestreview-508365958 and https://github.com/rust-bitcoin/rust-bitcoin/pull/501#discussion_r504746847

**Comment by JeremyRubin** [comment]
renamed feature to schemars

**Comment by apoelstra** [comment]
Can you give exact instructions to reproduce your issue?

**Comment by JeremyRubin** [comment]
Hi. Start with the branch jsonschemars from #501 

patch it to remove the fix I'm suggesting, and pin bitcoin_hashes to 0.9.0 till the 0.9.2 comes out ;).

```diff
diff --git a/Cargo.toml b/Cargo.toml
index ca94885..54a9026 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -25,7 +25,7 @@ secp-recovery = ["secp256k1/recovery"]
 [dependencies]
 base64-compat = { version = "1.0.0", optional = true }
 bech32 = "0.7.2"
-bitcoin_hashes = "0.9.0"
+bitcoin_hashes = "=0.9.0"
 secp256k1 = { version = "0.19.0", features = [ "recovery" ] }
 
 bitcoinconsensus = { version = "0.19.0-1", optional = true }
@@ -36,8 +36,8 @@ version = "0.8.0"
 optional = true
 
 [dev-dependencies]
-serde_derive = "<1.0.99, >= 1.0.0"
-serde_json = "<1.0.45, >= 1.0.0"
+serde_derive = "<1.0.99"
+serde_json = "<1.0.45"
 serde_test = "1"
 secp256k1 = { version = "0.19.0", features = [ "recovery", "rand-std" ] }
 jsonschema-valid = "0.2.0"


```

rm Cargo.lock + cargo clean or whatever.

```
error[E0433]: failed to resolve: could not find `SeqVisitor` in `de`
    --> src/util/amount.rs:1460:29
     |
1460 |         #[derive(Serialize, Deserialize, PartialEq, Debug)]
     |                             ^^^^^^^^^^^ could not find `SeqVisitor` in `de`
     |
     = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0433]: failed to resolve: could not find `MapVisitor` in `de`
    --> src/util/amount.rs:1460:29
     |
1460 |         #[derive(Serialize, Deserialize, PartialEq, Debug)]
     |                             ^^^^^^^^^^^ could not find `MapVisitor` in `de`
     |
     = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0433]: failed to resolve: could not find `SeqVisitor` in `de`
    --> src/util/amount.rs:1492:29
     |
1492 |         #[derive(Serialize, Deserialize, PartialEq, Debug)]
     |                             ^^^^^^^^^^^ could not find `SeqVisitor` in `de`
     |
     = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0433]: failed to resolve: could not find `MapVisitor` in `de`
    --> src/util/amount.rs:1492:29
     |
1492 |         #[derive(Serialize, Deserialize, PartialEq, Debug)]
     |                             ^^^^^^^^^^^ could not find `MapVisitor` in `de`
     |
     = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0433]: failed to resolve: could not find `SeqVisitor` in `de`
    --> src/util/amount.rs:1526:29
     |
1526 |         #[derive(Serialize, Deserialize, PartialEq, Debug)]
     |                             ^^^^^^^^^^^ could not find `SeqVisitor` in `de`
     |
     = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0433]: failed to resolve: could not find `MapVisitor` in `de`
    --> src/util/amount.rs:1526:29
     |
1526 |         #[derive(Serialize, Deserialize, PartialEq, Debug)]
     |                             ^^^^^^^^^^^ could not find `MapVisitor` in `de`
     |
     = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0433]: failed to resolve: could not find `SeqVisitor` in `de`
    --> src/util/amount.rs:1562:29
     |
1562 |         #[derive(Serialize, Deserialize, Debug, PartialEq, schemars::JsonSchema)]
     |                             ^^^^^^^^^^^ could not find `SeqVisitor` in `de`
     |
     = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0405]: cannot find trait `SeqVisitor` in module `_serde::de`
    --> src/util/amount.rs:1460:29
     |
1460 |         #[derive(Serialize, Deserialize, PartialEq, Debug)]
     |                             ^^^^^^^^^^^ help: a trait with a similar name exists: `Visitor`
     | 
    ::: /home/jr/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.117/src/de/mod.rs:1263:1
     |
1263 | pub trait Visitor<'de>: Sized {
     | ----------------------------- similarly named trait `Visitor` defined here
     |
     = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0405]: cannot find trait `MapVisitor` in module `_serde::de`
    --> src/util/amount.rs:1460:29
     |
1460 |         #[derive(Serialize, Deserialize, PartialEq, Debug)]
     |                             ^^^^^^^^^^^ help: a trait with a similar name exists: `Visitor`
     | 
    ::: /home/jr/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.117/src/de/mod.rs:1263:1
     |
1263 | pub trait Visitor<'de>: Sized {
     | ----------------------------- similarly named trait `Visitor` defined here
     |
     = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0412]: cannot find type `IgnoredAny` in `_serde::de::impls`
    --> src/util/amount.rs:1460:29
     |
1460 |         #[derive(Serialize, Deserialize, PartialEq, Debug)]
     |                             ^^^^^^^^^^^ not found in `_serde::de::impls`
     |
     = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider importing this struct
     |
1178 |     use serde::de::IgnoredAny;
     |

error[E0405]: cannot find trait `SeqVisitor` in module `_serde::de`
    --> src/util/amount.rs:1492:29
     |
1492 |         #[derive(Serialize, Deserialize, PartialEq, Debug)]
     |                             ^^^^^^^^^^^ help: a trait with a similar name exists: `Visitor`
     | 
    ::: /home/jr/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.117/src/de/mod.rs:1263:1
     |
1263 | pub trait Visitor<'de>: Sized {
     | ----------------------------- similarly named trait `Visitor` defined here
     |
     = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0405]: cannot find trait `MapVisitor` in module `_serde::de`
    --> src/util/amount.rs:1492:29
     |
1492 |         #[derive(Serialize, Deserialize, PartialEq, Debug)]
     |                             ^^^^^^^^^^^ help: a trait with a similar name exists: `Visitor`
     | 
    ::: /home/jr/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.117/src/de/mod.rs:1263:1
     |
1263 | pub trait Visitor<'de>: Sized {
     | ----------------------------- similarly named trait `Visitor` defined here
     |
     = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0412]: cannot find type `IgnoredAny` in `_serde::de::impls`
    --> src/util/amount.rs:1492:29
     |
1492 |         #[derive(Serialize, Deserialize, PartialEq, Debug)]
     |                             ^^^^^^^^^^^ not found in `_serde::de::impls`
     |
     = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider importing this struct
     |
1178 |     use serde::de::IgnoredAny;
     |

error[E0405]: cannot find trait `SeqVisitor` in module `_serde::de`
    --> src/util/amount.rs:1526:29
     |
1526 |         #[derive(Serialize, Deserialize, PartialEq, Debug)]
     |                             ^^^^^^^^^^^ help: a trait with a similar name exists: `Visitor`
     | 
    ::: /home/jr/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.117/src/de/mod.rs:1263:1
     |
1263 | pub trait Visitor<'de>: Sized {
     | ----------------------------- similarly named trait `Visitor` defined here
     |
     = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0405]: cannot find trait `MapVisitor` in module `_serde::de`
    --> src/util/amount.rs:1526:29
     |
1526 |         #[derive(Serialize, Deserialize, PartialEq, Debug)]
     |                             ^^^^^^^^^^^ help: a trait with a similar name exists: `Visitor`
     | 
    ::: /home/jr/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.117/src/de/mod.rs:1263:1
     |
1263 | pub trait Visitor<'de>: Sized {
     | ----------------------------- similarly named trait `Visitor` defined here
     |
     = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0412]: cannot find type `IgnoredAny` in `_serde::de::impls`
    --> src/util/amount.rs:1526:29
     |
1526 |         #[derive(Serialize, Deserialize, PartialEq, Debug)]
     |                             ^^^^^^^^^^^ not found in `_serde::de::impls`
     |
     = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider importing this struct
     |
1178 |     use serde::de::IgnoredAny;
     |

error[E0405]: cannot find trait `SeqVisitor` in module `_serde::de`
    --> src/util/amount.rs:1562:29
     |
1562 |         #[derive(Serialize, Deserialize, Debug, PartialEq, schemars::JsonSchema)]
     |                             ^^^^^^^^^^^ help: a trait with a similar name exists: `Visitor`
     | 
    ::: /home/jr/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.117/src/de/mod.rs:1263:1
     |
1263 | pub trait Visitor<'de>: Sized {
     | ----------------------------- similarly named trait `Visitor` defined here
     |
     = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0603]: module `impls` is private
    --> src/util/amount.rs:1460:29
     |
1460 |         #[derive(Serialize, Deserialize, PartialEq, Debug)]
     |                             ^^^^^^^^^^^ private module
     |
note: the module `impls` is defined here
    --> /home/jr/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.117/src/de/mod.rs:123:1
     |
123  | mod impls;
     | ^^^^^^^^^^

error[E0603]: module `impls` is private
    --> src/util/amount.rs:1492:29
     |
1492 |         #[derive(Serialize, Deserialize, PartialEq, Debug)]
     |                             ^^^^^^^^^^^ private module
     |
note: the module `impls` is defined here
    --> /home/jr/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.117/src/de/mod.rs:123:1
     |
123  | mod impls;
     | ^^^^^^^^^^

error[E0603]: module `impls` is private
    --> src/util/amount.rs:1526:29
     |
1526 |         #[derive(Serialize, Deserialize, PartialEq, Debug)]
     |                             ^^^^^^^^^^^ private module
     |
note: the module `impls` is defined here
    --> /home/jr/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.117/src/de/mod.rs:123:1
     |
123  | mod impls;
     | ^^^^^^^^^^

error[E0726]: implicit elided lifetime not allowed here
    --> src/util/amount.rs:1460:29
     |
1460 |         #[derive(Serialize, Deserialize, PartialEq, Debug)]
     |                             ^^^^^^^^^^^- help: indicate the anonymous lifetime: `<'_>`
     |
     = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0726]: implicit elided lifetime not allowed here
    --> src/util/amount.rs:1492:29
     |
1492 |         #[derive(Serialize, Deserialize, PartialEq, Debug)]
     |                             ^^^^^^^^^^^- help: indicate the anonymous lifetime: `<'_>`
     |
     = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0726]: implicit elided lifetime not allowed here
    --> src/util/amount.rs:1526:29
     |
1526 |         #[derive(Serialize, Deserialize, PartialEq, Debug)]
     |                             ^^^^^^^^^^^- help: indicate the anonymous lifetime: `<'_>`
     |
     = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0726]: implicit elided lifetime not allowed here
    --> src/util/amount.rs:1562:29
     |
1562 |         #[derive(Serialize, Deserialize, Debug, PartialEq, schemars::JsonSchema)]
     |                             ^^^^^^^^^^^- help: indicate the anonymous lifetime: `<'_>`
     |
     = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0106]: missing lifetime specifier
    --> src/util/amount.rs:1460:29
     |
1460 |         #[derive(Serialize, Deserialize, PartialEq, Debug)]
     |                             ^^^^^^^^^^^ expected named lifetime parameter
     |
     = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider introducing a named lifetime parameter
     |
1460 |         #[derive(Serialize, 'a, Deserialize<'a>, PartialEq, Debug)]
     |                             ^^^^^^^^^^^^^^^

error[E0106]: missing lifetime specifier
    --> src/util/amount.rs:1492:29
     |
1492 |         #[derive(Serialize, Deserialize, PartialEq, Debug)]
     |                             ^^^^^^^^^^^ expected named lifetime parameter
     |
     = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider introducing a named lifetime parameter
     |
1492 |         #[derive(Serialize, 'a, Deserialize<'a>, PartialEq, Debug)]
     |                             ^^^^^^^^^^^^^^^

error[E0106]: missing lifetime specifier
    --> src/util/amount.rs:1526:29
     |
1526 |         #[derive(Serialize, Deserialize, PartialEq, Debug)]
     |                             ^^^^^^^^^^^ expected named lifetime parameter
     |
     = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider introducing a named lifetime parameter
     |
1526 |         #[derive(Serialize, 'a, Deserialize<'a>, PartialEq, Debug)]
     |                             ^^^^^^^^^^^^^^^

error[E0106]: missing lifetime specifier
    --> src/util/amount.rs:1562:29
     |
1562 |         #[derive(Serialize, Deserialize, Debug, PartialEq, schemars::JsonSchema)]
     |                             ^^^^^^^^^^^ expected named lifetime parameter
     |
     = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider introducing a named lifetime parameter
     |
1562 |         #[derive(Serialize, 'a, Deserialize<'a>, Debug, PartialEq, schemars::JsonSchema)]
     |                             ^^^^^^^^^^^^^^^

error: aborting due to 28 previous errors

Some errors have detailed explanations: E0106, E0405, E0412, E0433, E0603.
For more information about an error, try `rustc --explain E0106`.
error: could not compile `bitcoin`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed

```

**Comment by JeremyRubin** [comment]
Here's two lock files:

[Cargo-incorrect.lock.txt](https://github.com/rust-bitcoin/rust-bitcoin/files/5394626/cargo.lock.txt)
[Cargo-correct.lock.txt](https://github.com/rust-bitcoin/rust-bitcoin/files/5394627/Cargo-correct.lock.txt)

you can see that for some reason:
```
"serde_derive 0.9.15",
"serde_json 0.9.10",
```

get pulled in.

**Comment by stevenroose** [comment]
https://github.com/rust-bitcoin/rust-bitcoin/pull/508 this PR might be relevant to this one. I didn't read the entire conversation, though.

**Comment by apoelstra** [comment]
Curious if this is still an issue since we fixed CI on bitcoin_hashes.

**Comment by dr-orlovsky** [comment]
Will be outdated once #635 gets merged

**Comment by apoelstra** [comment]
Closing since I believe it was fixed by rustc 1.41/2018, and our current `Cargo.toml` does not have any version constraints like this anymore.
