### ISSUE TITLE
"cargo test" broke due to rust-secp upgrade

### ISSUE THREAD

**Issue by laanwj** [rust-bitcoin/rust-bitcoin#161]
```
   Compiling bitcoin v0.14.1 (file:///home/user/bitcoin/rust-bitcoin)
error[E0277]: the trait bound `rand::ThreadRng: rand::Rng` is not satisfied
   --> src/util/contracthash.rs:346:31
    |
346 |         let (sk1, pk1) = secp.generate_keypair(&mut thread_rng());
    |                               ^^^^^^^^^^^^^^^^ the trait `rand::Rng` is not implemented for `rand::ThreadRng`
error[E0277]: the trait bound `rand::ThreadRng: rand::Rng` is not satisfied
   --> src/util/contracthash.rs:347:31
    |
347 |         let (sk2, pk2) = secp.generate_keypair(&mut thread_rng());
    |                               ^^^^^^^^^^^^^^^^ the trait `rand::Rng` is not implemented for `rand::ThreadRng`
error[E0277]: the trait bound `rand::ThreadRng: rand::Rng` is not satisfied
   --> src/util/contracthash.rs:348:31
    |
348 |         let (sk3, pk3) = secp.generate_keypair(&mut thread_rng());
    |                               ^^^^^^^^^^^^^^^^ the trait `rand::Rng` is not implemented for `rand::ThreadRng`
error: aborting due to 3 previous errors
```

bisected it to:
```
41ebf5468c01a8411b41d8a3d5d9fcb807cc1d49 is the first bad commit
commit 41ebf5468c01a8411b41d8a3d5d9fcb807cc1d49
Author: Andrew Poelstra <apoelstra@wpsoftware.net>
Date:   Wed Aug 22 19:37:32 2018 +0000
    update rust-secp dependency to 0.11
:100644 100644 7902134f3d96ecee1d4f74800089cf452bee4bf9 5f14d7388eaeb02fde3c0cee3b620a31577113ce M      Cargo.toml
```

(this is with rust stable `rustc 1.28.0 (9634041f0 2018-07-30)`)

**Comment by apoelstra** [comment]
Can anyone reproduce this?

**Comment by TheBlueMatt** [comment]
I havent seen it, weirdly enough, but the proposed fix looks good to me either way.

**Comment by apoelstra** [comment]
Unfortunately the proposed fix technically requires a major version bump, since we implement `rand::Rand` on a pile of our types and people could be depending on that.

**Comment by laanwj** [comment]
I could no longer reproduce this after `git clean -f -x -d`, so closing
