### PR TITLE
Separate signature hash types

### LINKED ISSUE #670: Why do we have two `SigHashType`s?
First one: 

https://github.com/rust-bitcoin/rust-bitcoin/blob/master/src/blockdata/transaction.rs#L676-L695

Second one:

https://github.com/rust-bitcoin/rust-bitcoin/blob/master/src/util/sighash.rs#L102-L126

### PR DESCRIPTION
**Pull request by sanket1729**
Fixes #670 . Separates `SchnorrSigHashType` and `LegacySigHashType`. Also adds the following new structs:

```rust
pub struct SchnorrSig {
    /// The underlying schnorr signature
    pub sig: secp256k1::schnorrsig::Signature,
    /// The corresponding hash type
    pub hash_ty: SchnorrSigHashType,
}

pub struct EcdsaSig {
    /// The underlying DER serialized Signature
    pub sig: secp256k1::Signature,
    /// The corresponding hash type
    pub hash_ty: LegacySigHashType,
}
```

This code is currently minimal to aid reviews. We can at a later point implement (Encodeable, psbt::Serialize, FromHex, ToHex) etc in follow-up PRs.

### CODE REVIEW

File: src/blockdata/transaction.rs [hunk 1]
```diff
@@ -673,10 +673,15 @@ impl fmt::Display for NonStandardSigHashType {
...
+/// Legacy Hashtype of an input's signature
+#[deprecated(since="0.28.0", note="Please use [`LegacySigHashType`] instead")]
+pub type SigHashType = LegacySigHashType;
+
 /// Hashtype of an input's signature, encoded in the last byte of the signature
 /// Fixed values so they can be casted as integer types for encoding
+/// See also [`crate::SchnorrSigHashType`]
 #[derive(PartialEq, Eq, Debug, Copy, Clone)]
-pub enum SigHashType {
+pub enum LegacySigHashType {
```
Comment (dr-orlovsky) [inline src/blockdata/transaction.rs:684]: nit: Why not `EcdsaSigHashType`?  One still have to use this type in all non-BIP-340 contexts, so not sure whether it is actually "legacy".

File: src/blockdata/transaction.rs [hunk 2]
```diff
@@ -693,92 +698,92 @@ pub enum SigHashType {
     /// 0x83: Sign one output and only this input (see `Single` for what "one output" means)
     SinglePlusAnyoneCanPay	= 0x83
 }
-serde_string_impl!(SigHashType, "a SigHashType data");
+serde_string_impl!(LegacySigHashType, "a SigHashType data");
```
Comment (dr-orlovsky) [inline src/blockdata/transaction.rs:701]:
```suggestion
serde_string_impl!(LegacySigHashType, "a LegacySigHashType data");
```

File: src/util/ecdsa.rs [hunk 3]
```diff
@@ -412,6 +416,72 @@ impl<'de> ::serde::Deserialize<'de> for PublicKey {
...
+                Ok(EcdsaSig { sig, hash_ty })
+            },
+            None => {
+                Err(EcdsaSigError::Secp256k1(secp256k1::Error::InvalidSignature))?
+            },
+        }
+    }
+
+    /// Serialize EcdsaSig
+    pub fn serialize(&self) -> Vec<u8> {
```
Comment (dr-orlovsky) [inline src/util/ecdsa.rs:446]: Shouldn't this be a `Encode` impl? I assume this is "consensus serialization". Also, why not to have `Decode` impl.

File: src/util/ecdsa.rs [hunk 4]
```diff
@@ -412,6 +416,72 @@ impl<'de> ::serde::Deserialize<'de> for PublicKey {
...
+    pub fn from_slice(sl: &[u8]) -> Result<Self, EcdsaSigError> {
+        match sl.split_last() {
+            Some((hash_ty, sig)) => {
+                let hash_ty = LegacySigHashType::from_u32_standard(*hash_ty as u32)
+                    .map_err(|_| EcdsaSigError::NonStandardSigHashType(*hash_ty))?;
+                let sig = secp256k1::Signature::from_der(sig)?;
+                Ok(EcdsaSig { sig, hash_ty })
+            },
+            None => {
+                Err(EcdsaSigError::Secp256k1(secp256k1::Error::InvalidSignature))?
```
Comment (dr-orlovsky) [inline src/util/ecdsa.rs:440]: Well, it is not an ECDSA signature which is invalid, it is bitcoin-specific tx input serialization which misses sighashtype. So I think this should be a dedicated error type.

File: src/util/schnorr.rs [hunk 5]
```diff
@@ -75,9 +79,71 @@ impl TweakedPublicKey {
...
+    pub sig: secp256k1::schnorrsig::Signature,
+    /// The corresponding hash type
+    pub hash_ty: SchnorrSigHashType,
+}
+
+impl SchnorrSig {
+
+    /// Deserialize from slice
+    pub fn from_slice(sl: &[u8]) -> Result<Self, SchnorrSigError> {
+        match sl.split_last() {
```
Comment (dr-orlovsky) [inline src/util/schnorr.rs:102]: We have standardness requirements for  signature lengths, so I think logic should be structured in different way than in `LegacySig` providing more specific error types.

File: src/util/schnorr.rs [hunk 6]
```diff
@@ -75,9 +79,71 @@ impl TweakedPublicKey {
...
+        // TODO: add support to serialize to a writer to SerializedSig
+        let mut ser_sig = self.sig.as_ref().to_vec();
+        ser_sig.push(self.hash_ty as u8);
+        ser_sig
+    }
+}
+
+/// A key-related error.
+#[derive(Clone, PartialEq, Eq, PartialOrd, Ord, Hash, Debug)]
+pub enum SchnorrSigError {
```
Comment (dr-orlovsky) [inline src/util/schnorr.rs:126]: Are we sure that we need a dedicated error type for each of sigs?

File: src/util/schnorr.rs [hunk 7]
```diff
@@ -75,9 +79,71 @@ impl TweakedPublicKey {
...
+                Ok(SchnorrSig { sig, hash_ty })
+            },
+            None => {
+                Err(SchnorrSigError::Secp256k1(secp256k1::Error::InvalidSignature))?
+            },
+        }
+    }
+
+    /// Serialize SchnorrSig
+    pub fn serialize(&self) -> Vec<u8> {
```
Comment (dr-orlovsky) [inline src/util/schnorr.rs:116]: The same question with implementing `Encode`/`Decode` as above

**Review by dr-orlovsky — COMMENTED** [review]
Left some comments and questions

File: src/util/schnorr.rs (hunk 6 above)
Comment (Kixunil) [reply src/util/schnorr.rs:126]: Didn't you imply it above? :)

Comment (dr-orlovsky) [reply src/util/schnorr.rs:126]: Above I meant dedicated error variants, not types. Sorry for spelling thad badly

Comment (Kixunil) [reply src/util/schnorr.rs:126]: I personally like keeping error types separate so that impossible error cases don't need to be handled by the callers. But I do understand most people probably find it annoying, especially if there are many error types and they want to just return a common type. One of my ten billion project ideas is having a (proc) macro generate "subset" error types (so you can have one common `Error` for library and then other errors with variants that are strict subsets and convertible to the common `Error`)...

File: src/util/ecdsa.rs (hunk 4 above)
Comment (sanket1729) [reply src/util/ecdsa.rs:440]: I thought about this, and I think we can get away from this here. From an implementation point of view, it appears that we are missing the last byte from the slice (because the slice is empty), but that also means the underlying signature is invalid. 

There is really no way to know if we are missing the first byte of the sig, or the last byte (sighash byte)

File: src/util/schnorr.rs (hunk 6 above)
Comment (sanket1729) [reply src/util/schnorr.rs:126]: I try to separate error types for the exact same reason. It is really hard to write code downstream that does anything apart from propagating the error forward.

File: src/util/schnorr.rs (hunk 7 above)
Comment (sanket1729) [reply src/util/schnorr.rs:116]: As mentioned in the above PR description, I did not want to clutter this PR with additional stuff. And there are a few subtle reasons why I did not implement this, or whether the Encodable even makes sense.

Encodable defines a bitcoin network serialization format. And signatures are always sent as witness data with serialization implemented for `Vec<Vec<u8>>`. This is the same reason why I did not define Encode/Decode trait methods for `ControlBlock`, `TaprootMerkleRoot` in #677 because they are a part of witness data. It might even create confusion whether the `Encodeable` includes the VarInt prefix in witness format or not. I was not involved in early rust-bitcoin days, but I presume this is the same reason why `Encode\Deocde` is not done for `bitcoin::PublicKey`

This is why I chose to implement methods directly on the type

File: src/util/schnorr.rs (hunk 6 above)
Comment (dr-orlovsky) [reply src/util/schnorr.rs:132]: Yeah, I always have dedicated error types in my projects, unless all of the options for two error types are the same (like in this case).

File: src/util/ecdsa.rs (hunk 4 above)
Comment (dr-orlovsky) [reply src/util/ecdsa.rs:440]: Agree that we can't detect is signature is wrong or sighashtype is absent; but it is clearly not a Secp error but a dedicated variant `InvalidSigOrMissedSigHash` :)

File: src/util/schnorr.rs (hunk 6 above)
Comment (Kixunil) [reply src/util/schnorr.rs:132]: Ah, true, they have same variants. I think it'd make sense to unify them unless there's expectation they will change in the future. Seems unlikely?

File: src/util/ecdsa.rs (hunk 4 above)
Comment (sanket1729) [reply src/util/ecdsa.rs:440]: I don't mean to be pedantic here. Would it be okay if I replace the following 
```diff
- Err(EcdsaSigError::Secp256k1(secp256k1::Error::InvalidSignature))?
+ secp256k1::Signature::from_slice(sl)?
```

I don't want to add unnecessary error variants that don't represent any meaning for the caller. I have partially started changing some code in `rust-miniscript` to actually deal with error types sanely rather than just propagating them.

File: src/util/schnorr.rs (hunk 6 above)
Comment (sanket1729) [reply src/util/schnorr.rs:132]: They are slightly different types. Because while parsing `EcdsaSig` we have NonStandardSigHashType, whereas while parsing `SchnorrSig` we have `InvalidSigHashType`. 

Types apart from standard 6 types automatically are treated as SIGHASH_ALL or `ALL|ACP`. But the point is 0x04 is a valid consensus ECDSA sighash type, but 0x04 is consensus invalid `SchnorrSighashType`. I had specifically named them `NonStandard` and `Invalid` for this reason.

File: src/util/ecdsa.rs (hunk 4 above)
Comment (dr-orlovsky) [reply src/util/ecdsa.rs:440]: I am neither won't to be pedantic. I am just not follow your line of thoughts.

From what I see, there is a special data type representing the way ECDSA signature AND sighash are present in witness/scriptSig data - that is why we introduce these two new types.

And we can't distinguish situation from when the signature is badly serialized, contains invalid public keys or sighashtype is not present in ECDSA. These all are indistinguishable error types AND it is not the same as usual `secp256k1::Error` - none of its variants.

The second option for ECDSA witness/scriptSig data is that we have a proper signature and improper sighashtype (non-standard), i.e. existing `EcdsaSigError::NonStandardSigHashType`.

So I see having 
```rust
pub enum EcdsaSigError {
    NonStandardSigHashType,
    UnparsableData
}
```
to be more specific, not less specific.

With `SchnorrSig` we have different situation. There _we can_ distinguish improperly serialized signature from invalid `SigHashType`, since the signature always have 64 bytes in length. Thus, we have a different set of error variants, and there it will be correct to wrap `secp256k1::Error` for signature deserialization and add second option `InvalidSigHashType`. However, the parsing algorithm should be different from the one used for `EcdsaSig`.

Thus is a summary of all my comments in this PR.

File: src/util/schnorr.rs (hunk 6 above)
Comment (Kixunil) [reply src/util/schnorr.rs:132]: Ah, I agree with having them separated then.

File: src/util/ecdsa.rs (hunk 4 above)
Comment (sanket1729) [reply src/util/ecdsa.rs:440]: 100% Agreed with this suggestion.

File: src/blockdata/transaction.rs (hunk 1 above)
Comment (RCasatta) [reply src/blockdata/transaction.rs]: Maybe you can rename also the commit message with `EcdsaSigHashType`

**Comment by sanket1729** [comment]
Ready for review again.

File: src/util/schnorr.rs [hunk 8]
```diff
@@ -76,9 +80,77 @@ impl TweakedPublicKey {
...
+        // TODO: add support to serialize to a writer to SerializedSig
+        let mut ser_sig = self.sig.as_ref().to_vec();
+        ser_sig.push(self.hash_ty as u8);
+        ser_sig
+    }
+}
+
+/// A schnorr sig related error.
+#[derive(Clone, PartialEq, Eq, PartialOrd, Ord, Hash, Debug)]
+pub enum SchnorrSigError {
```
Comment (thomaseizinger) [inline src/util/schnorr.rs:133]: This is missing an impl for `std::error::Error`.

File: src/util/schnorr.rs [hunk 9]
```diff
@@ -76,9 +80,77 @@ impl TweakedPublicKey {
...
+                },
+                None => {
+                    Err(SchnorrSigError::Secp256k1(secp256k1::Error::InvalidSignature))?
+                },
+            }
+        }
+    }
+
+    /// Serialize SchnorrSig
+    pub fn serialize(&self) -> Vec<u8> {
```
Comment (thomaseizinger) [inline src/util/schnorr.rs:123]: For uniformity, we could consider naming this `to_vec` instead.

If there is a `serialize`, I would expect a `deserialize` but that one is called `from_slice`.

File: src/util/schnorr.rs [hunk 10]
```diff
@@ -76,9 +80,77 @@ impl TweakedPublicKey {
...
+            match sl.split_last() {
+                Some((hash_ty, sig)) => {
+                    let hash_ty = SchnorrSigHashType::from_u8(*hash_ty)
+                        .map_err(|_| SchnorrSigError::InvalidSighashType(*hash_ty))?;
+                    let sig = secp256k1::schnorrsig::Signature::from_slice(sig)?;
+                    Ok(SchnorrSig { sig, hash_ty })
+                },
+                None => {
+                    Err(SchnorrSigError::Secp256k1(secp256k1::Error::InvalidSignature))?
+                },
```
Comment (thomaseizinger) [inline src/util/schnorr.rs:117]: This could be written as an `ok_or_else` after the `split_last`. That would get rid of the explicit pattern match.

File: src/util/schnorr.rs [hunk 11]
```diff
@@ -76,9 +80,77 @@ impl TweakedPublicKey {
...
+}
+
+impl SchnorrSig {
+
+    /// Deserialize from slice
+    pub fn from_slice(sl: &[u8]) -> Result<Self, SchnorrSigError> {
+        if sl.len() == SCHNORRSIG_SIGNATURE_SIZE {
+            // default type
+            let sig = secp256k1::schnorrsig::Signature::from_slice(sl)?;
+            Ok( SchnorrSig { sig, hash_ty : SchnorrSigHashType::Default })
```
Comment (thomaseizinger) [inline src/util/schnorr.rs:106]: Could early return here and get rid of the `else` block. Would reduce another indentation level of the code below.

**Review by thomaseizinger — COMMENTED** [review]
Few ideas :)

File: src/util/schnorr.rs (hunk 9 above)
Comment (Kixunil) [reply src/util/schnorr.rs:123]: I believe it should return `[u8; 64]` instead of `Vec`

File: src/util/schnorr.rs (hunk 8 above)
Comment (Kixunil) [reply src/util/schnorr.rs:133]: And don't forget about `cfg` and `doc(cfg)`

File: src/util/ecdsa.rs [hunk 12]
```diff
@@ -413,6 +417,66 @@ impl<'de> ::serde::Deserialize<'de> for PublicKey {
...
+    pub sig: secp256k1::Signature,
+    /// The corresponding hash type
+    pub hash_ty: EcdsaSigHashType,
+}
+
+impl EcdsaSig {
+
+    /// Deserialize from slice
+    pub fn from_slice(sl: &[u8]) -> Result<Self, EcdsaSigError> {
+        match sl.split_last() {
```
Comment (Kixunil) [inline src/util/ecdsa.rs:433]: `let (hash_ty, sig) = sl.split_last().ok_or(EcdsaSigError::InvalidEcdsaSig)?;`
and get rid of indentation

File: src/util/schnorr.rs (hunk 10 above)
Comment (Kixunil) [reply src/util/schnorr.rs:117]: Also if this is kept, use `return Err(...)` instead of `Err(...)?`

File: src/util/schnorr.rs [hunk 13]
```diff
@@ -76,9 +80,77 @@ impl TweakedPublicKey {
...
+        }
+    }
+}
+
+#[doc(hidden)]
+impl From<secp256k1::Error> for SchnorrSigError {
+    fn from(e: secp256k1::Error) -> SchnorrSigError {
+        SchnorrSigError::Secp256k1(e)
+    }
 }
```
Comment (Kixunil) [inline src/util/schnorr.rs:156]: Add newline?

File: src/util/schnorr.rs [hunk 14]
```diff
@@ -76,9 +80,77 @@ impl TweakedPublicKey {
...
+    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
+        match *self {
+            SchnorrSigError::InvalidSighashType(hash_ty) =>
+                write!(f, "Invalid signature hash type {}", hash_ty),
+            SchnorrSigError::Secp256k1(ref e) => write!(f, "Key secp256k1 error: {}", e),
+        }
+    }
+}
+
+#[doc(hidden)]
```
Comment (Kixunil) [inline src/util/schnorr.rs:151]: I'm not convinced this helps much. Most people would probably blindly try `?` and thus start implicitly relying on it.

File: src/util/schnorr.rs (hunk 9 above)
Comment (sanket1729) [reply src/util/schnorr.rs:123]: It could return either 64 bytes or 65 bytes depending on sighash type

Comment (Kixunil) [reply src/util/schnorr.rs:123]: Ah, shame!

File: src/util/schnorr.rs (hunk 14 above)
Comment (sanket1729) [reply src/util/schnorr.rs:151]: This is how it is done throughout the library. I never really thought if this was useful or not, but just have the hidden as a rule :( .

File: src/util/ecdsa.rs [hunk 15]
```diff
@@ -413,6 +417,61 @@ impl<'de> ::serde::Deserialize<'de> for PublicKey {
     }
 }
 
+/// An ECDSA signature with the corresponding hash type.
+#[derive(Debug, Copy, Clone, PartialEq, Eq)]
```
Comment (dr-orlovsky) [inline src/util/ecdsa.rs:421]: `#[derive(PartialOrd, Ord, Hash]`

File: src/util/schnorr.rs [hunk 16]
```diff
@@ -76,9 +80,80 @@ impl TweakedPublicKey {
...
+    /// Returns the underlying public key
     pub fn into_inner(self) -> PublicKey {
         self.0
     }
-}
\ No newline at end of file
+}
+
+/// A BIP340-341 serialized schnorr signature with the corresponding hash type.
+#[derive(Debug, Copy, Clone, PartialEq, Eq)]
```
Comment (dr-orlovsky) [inline src/util/schnorr.rs:91]:
```suggestion
#[derive(Debug, Copy, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
```

**Review by dr-orlovsky — CHANGES_REQUESTED** [review]
re-ACK with two small improvements since needs rebase anyway

File: src/util/ecdsa.rs (hunk 15 above)
Comment (Kixunil) [reply src/util/ecdsa.rs:421]: What does it mean for signature to be greater than other signature? Doesn't seem intuitive for me. I agree with `Hash`.

Comment (dr-orlovsky) [reply src/util/ecdsa.rs:421]: It means that they can be used as keys in `BTreeMap` or be put into `BTreeSet`. Maps are important for stuff like PSBTs.

Signatures _do_ implement `Ord` in secp library (both in rust and C versions), so this should be followed here as well, I assume

Comment (Kixunil) [reply src/util/ecdsa.rs:421]: For PSBTs and such I'd expect maps to be keyed by the key (:D) not signature. However if this is widely implemented then I agree with adding it as long as ordering works the same as in other sw.

Comment (dr-orlovsky) [reply src/util/ecdsa.rs:421]: PSBTs are indeed keyed not by signatures, but I can well imagine wallets needing to key some data by signatures

Comment (sanket1729) [reply src/util/ecdsa.rs:421]: Only `Ord, PartialOrd` can be auto derived for SchnorrSig. `PartialOrd, Ord, Hash` cannot be derived for `EcdsaSig`. Added `Ord, PartialOrd` for now

**Comment by sanket1729** [comment]
Rebased

File: src/util/schnorr.rs [hunk 17]
```diff
@@ -85,4 +89,75 @@ impl TweakedPublicKey {
...
+
+    /// Deserialize from slice
+    pub fn from_slice(sl: &[u8]) -> Result<Self, SchnorrSigError> {
+        if sl.len() == SCHNORRSIG_SIGNATURE_SIZE {
+            // default type
+            let sig = secp256k1::schnorrsig::Signature::from_slice(sl)?;
+            return Ok( SchnorrSig { sig, hash_ty : SchnorrSigHashType::Default });
+        }
+        let (hash_ty, sig) = sl.split_last()
+            .ok_or_else(|| secp256k1::Error::InvalidSignature)?;
```
Comment (dr-orlovsky) [inline src/util/schnorr.rs:113]: Ibid

File: src/util/schnorr.rs [hunk 18]
```diff
@@ -85,4 +89,75 @@ impl TweakedPublicKey {
...
+        let hash_ty = SchnorrSigHashType::from_u8(*hash_ty)
+            .map_err(|_| SchnorrSigError::InvalidSighashType(*hash_ty))?;
+        let sig = secp256k1::schnorrsig::Signature::from_slice(sig)?;
+        Ok(SchnorrSig { sig, hash_ty })
```
Comment (dr-orlovsky) [inline src/util/schnorr.rs:117]: I am not conveinced that case when we have 36 byte signature should error with `InvalidSighashType` in random manner :(

I mean that error that will fire in fact will depend on the value of the last byte even for signatures of incorrect length which certainly do not have sighash attached.

We either need dedicated error (Signature and sighash are incorrect) - or should distinguish incorrect sighash in 65 byte sig from incorrect sig in <64 case.

File: src/util/schnorr.rs [hunk 19]
```diff
@@ -85,4 +89,75 @@ impl TweakedPublicKey {
...
+    }
+
+    /// Serialize SchnorrSig
+    pub fn to_vec(&self) -> Vec<u8> {
+        // TODO: add support to serialize to a writer to SerializedSig
+        let mut ser_sig = self.sig.as_ref().to_vec();
+        if let SchnorrSigHashType::Default = self.hash_ty {
```
Comment (dr-orlovsky) [inline src/util/schnorr.rs:124]: Nit: we do not need `let` here
```suggestion
        if SchnorrSigHashType::Default == self.hash_ty {
```

File: src/util/schnorr.rs [hunk 20]
```diff
@@ -85,4 +89,75 @@ impl TweakedPublicKey {
...
+            // default sighash type, don't add extra sighash byte
+        } else {
+            ser_sig.push(self.hash_ty as u8);
+        }
```
Comment (dr-orlovsky) [inline src/util/schnorr.rs:128]: Overall, this can be simplified into
```suggestion
        if self.hash_ty != SchnorrSigHashType::Default {
           ser_sig.push(self.hash_ty as u8);
        }
```

File: src/util/sighash.rs [hunk 21]
```diff
@@ -229,31 +233,45 @@ impl<'s> ScriptPath<'s> {
...
+            SchnorrSigHashType::Single => (SchnorrSigHashType::Single, false),
+            SchnorrSigHashType::AllPlusAnyoneCanPay => (SchnorrSigHashType::All, true),
+            SchnorrSigHashType::NonePlusAnyoneCanPay => (SchnorrSigHashType::None, true),
+            SchnorrSigHashType::SinglePlusAnyoneCanPay => (SchnorrSigHashType::Single, true),
+            SchnorrSigHashType::Reserved => (SchnorrSigHashType::Reserved, false),
+        }
+    }
+
+    /// Create a [`SchnorrSigHashType`] from raw u8
+    pub fn from_u8(hash_ty: u8) -> Result<Self, Error> {
```
Comment (dr-orlovsky) [inline src/util/sighash.rs:265]: Nit: probably we create it from a byte value, not `u8`. I.e. `from_byte` may be more "consensus-style"

**Review by dr-orlovsky — APPROVED** [review]
ACK ace924e1f7095ea3d5f8d366e43dbc1dd862519b

I think all of my comments are just nits on coding style. One really non-stylish thing is returning more clear error from a schnorr witness signature parser, but again I would not postpone further taproot progress just because of error handling UX.

File: src/util/schnorr.rs (hunk 19 above)
Comment (tcharding) [reply src/util/schnorr.rs:124]: Perhaps its clearer the other way around
```
if self.hash_ty == SchnorrSigHashType::Default {
```

File: src/util/schnorr.rs (hunk 20 above)
Comment (sanket1729) [reply src/util/schnorr.rs:128]: Agreed with all the above nits, but I think the comment and explicit `if/else` have some value here in the form of documentation. I will fix the above nits, but I would like to keep this one as is.

File: src/util/schnorr.rs (hunk 18 above)
Comment (sanket1729) [reply src/util/schnorr.rs]: How do you feel about the new changes?

File: src/util/schnorr.rs (hunk 19 above)
Comment (sanket1729) [reply src/util/schnorr.rs]: Done

**Review by dr-orlovsky — DISMISSED** [review]
utACK 681acd18a2f16eaca731da93e6f68fdeb28ea6fe

File: src/util/schnorr.rs (hunk 18 above)
Comment (dr-orlovsky) [reply src/util/schnorr.rs]: That's exactly what I hoped for :)

**Comment by dr-orlovsky** [comment]
Can pls @Kixunil or @RCasatta review this PR such we can move forward with one of these Taproot release blockers?

File: src/util/ecdsa.rs [hunk 22]
```diff
@@ -22,13 +22,17 @@ use prelude::*;
 use core::{ops, str::FromStr};
 use core::fmt::{self, Write as _fmtWrite};
 use io;
+#[cfg(feature = "std")]
+use std::error;
```
Comment (RCasatta) [inline src/util/ecdsa.rs:26]: nit: since it's used only in `impl error::Error` using `impl std::error::Error` would save this two lines

**Review by RCasatta — APPROVED** [review]
ACK 681acd18a2f16eaca731da93e6f68fdeb28ea6fe

left a nit, but it's so small I will merge anyway to avoid turnover time

**Comment by RCasatta** [comment]
can't merge needs rebase

**Comment by sanket1729** [comment]
Rebased and addressed the nit

File: src/util/ecdsa.rs (hunk 22 above)
Comment (sanket1729) [reply src/util/ecdsa.rs]: Does not work on 1.29 :(

 
error[E0658]: access to extern crates through prelude is experimental (see issue #44660)
   --> src/util/ecdsa.rs:471:6
    |
471 | impl std::error::Error for EcdsaSigError {}

**Comment by sanket1729** [comment]
Since, this already had two ACKS. 
```diff
 1:  b8c60c9 = 10:  f3207dd Add EcdsaSig
 2:  e9f8217 = 11:  602604d Rename sighash::SigHashType::SigHashType to SchnorrSigHashType
 3:  0588037 = 12:  96e1c79 Add SchnorrSigHashType::from_u8
 4:  09a55bc = 13:  d3275f2 Rename existing SigHashType to EcdsaSigHashType
 5:  681acd1 ! 14:  04c0bc6 Add SchnorrSig type
    @@ src/util/schnorr.rs
      pub use secp256k1::schnorrsig::{PublicKey, KeyPair};
     -use secp256k1::{Secp256k1, Verification};
     +use secp256k1::{self, Secp256k1, Verification};
    - use hashes::{Hash, HashEngine};
    + use hashes::Hash;
      use util::taproot::{TapBranchHash, TapTweakHash};
     +use SchnorrSigHashType;


```

**Comment by dr-orlovsky** [comment]
..and now it requires another re-base :( Seems like with all these PRs touching the same taproot code we will need to re-base all of the PRs after each PR merge :(

**Comment by sanket1729** [comment]
Rebased again

**Review by RCasatta — DISMISSED** [review]
utACK f60b14e50f2afa849c9019580de8721658d5a99d

**Comment by dr-orlovsky** [comment]
utACK f60b14e50f2afa849c9019580de8721658d5a99d

Was unable to test commit-wise since rust stable panics on one of the commits due to internal error.

Command that fails:
`cargo +stable test --verbose --features=use-serde`

Commit that fails: ed40f3d

**Comment by RCasatta** [comment]
> Commit that fails: ed40f3d

I can't reproduce, and is it also out of this PR commit's?

**Comment by sanket1729** [comment]
Rebased again after #721

**Comment by RCasatta** [comment]
ACK 5769744b74464be67f328e57b3f286a12703f6e6

File: src/util/ecdsa.rs [hunk 23]
```diff
@@ -413,6 +415,61 @@ impl<'de> ::serde::Deserialize<'de> for PublicKey {
...
+impl EcdsaSig {
+
+    /// Deserialize from slice
+    pub fn from_slice(sl: &[u8]) -> Result<Self, EcdsaSigError> {
+        let (hash_ty, sig) = sl.split_last()
+            .ok_or(EcdsaSigError::InvalidEcdsaSig)?;
+        let hash_ty = EcdsaSigHashType::from_u32_standard(*hash_ty as u32)
+            .map_err(|_| EcdsaSigError::NonStandardSigHashType(*hash_ty))?;
+        let sig = secp256k1::Signature::from_der(sig)
+            .map_err(|_| EcdsaSigError::InvalidEcdsaSig)?;
```
Comment (Kixunil) [inline src/util/ecdsa.rs:436]: Why throw out the errors?

File: src/util/schnorr.rs [hunk 24]
```diff
@@ -104,3 +107,80 @@ impl TweakedPublicKey {
...
+                let sig = secp256k1::schnorrsig::Signature::from_slice(sl)
+                    .map_err(|_| SchnorrSigError::MalformedSchnorrSig)?;
+                return Ok( SchnorrSig { sig, hash_ty : SchnorrSigHashType::Default });
+            },
+            65 => {
+                let (hash_ty, sig) = sl.split_last().expect("Slice len checked == 65");
+                let hash_ty = SchnorrSigHashType::from_u8(*hash_ty)
+                    .map_err(|_| SchnorrSigError::InvalidSighashType(*hash_ty))?;
+                let sig = secp256k1::schnorrsig::Signature::from_slice(sig)
+                    .map_err(|_| SchnorrSigError::MalformedSchnorrSig)?;
```
Comment (Kixunil) [inline src/util/schnorr.rs:136]: Another throwing away of errors

File: src/util/ecdsa.rs [hunk 25]
```diff
@@ -413,6 +415,61 @@ impl<'de> ::serde::Deserialize<'de> for PublicKey {
...
+    InvalidEcdsaSig,
+}
+
+
+impl fmt::Display for EcdsaSigError {
+    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
+        match *self {
+            EcdsaSigError::NonStandardSigHashType(hash_ty) =>
+                write!(f, "Non standard signature hash type {}", hash_ty),
+            EcdsaSigError::InvalidEcdsaSig => write!(f, "Invalid Ecdsa Sig"),
```
Comment (Kixunil) [inline src/util/ecdsa.rs:464]: Since this message is shown to the user it could be a bit nicer. E.g. "Invalid ECDSA signature"

Can be done in a separate PR because it doesn't affect API.

**Review by Kixunil — COMMENTED** [review]
Would've ACKed but I really don't like throwing away of error information. From my experience, it makes debugging harder.

If there's a rationale why throw it away I'd like to know.

File: src/util/ecdsa.rs (hunk 23 above)
Comment (sanket1729) [reply src/util/ecdsa.rs:436]: The earlier versions of the PR did capture the underlying errors. I did this in order to 
- Avoid all but one unreachable error states in `secp256k1::Error`. In this scenario, I did check that only one variant of error was being returned in the corresponding secp functions. 
- It would have required to me have another return error type for empty signature. I don't know if the end-user really cares about this error type when the signature is empty or if the signature is malformed. I want to avoid creating unnecessary error enums that are not useful, but it makes matching with them downstream even harder. 

I was recently convinced on rust discord by someone else that I should always capture because in case upstream secp changes error reporting, we might want to capture it. Changing it back to the way it was previously

**Comment by sanket1729** [comment]
@Kixunil captured the underlying error types.

File: src/util/ecdsa.rs [hunk 26]
```diff
@@ -413,6 +415,72 @@ impl<'de> ::serde::Deserialize<'de> for PublicKey {
...
+}
+
+impl EcdsaSig {
+
+    /// Deserialize from slice
+    pub fn from_slice(sl: &[u8]) -> Result<Self, EcdsaSigError> {
+        let (hash_ty, sig) = sl.split_last()
+            .ok_or(EcdsaSigError::EmptySignature)?;
+        let hash_ty = EcdsaSigHashType::from_u32_standard(*hash_ty as u32)
+            .map_err(|_| EcdsaSigError::NonStandardSigHashType(*hash_ty))?;
```
Comment (Kixunil) [inline src/util/ecdsa.rs:434]: May be nicer to match on `NonStandardSigHashType` (`map_err(|NonStandardSigHashType| EcdsaSigError::NonStandardSigHashType(*hash_ty)`) to protect against possible future refactors but not a big deal.

**Review by Kixunil — APPROVED** [review]
ACK 83611295187f951290bec41a9c4831dcdaa5edad

**Review by RCasatta — APPROVED** [review]
ACK 83611295187f951290bec41a9c4831dcdaa5edad
