### PR TITLE
feat: implement `unsigned_abs` method

### LINKED ISSUE #1247: Manual implementation of `abs` method
As of Rust 1.31.1 we have an `abs` method on signed integer types. We have manual implementations of `abs`, an artifact of our previous MSRV (Rust 1.29).

Example: https://github.com/rust-bitcoin/rust-bitcoin/blob/ed9012c25c937744028f92ed78cf4e17e41934e8/src/blockdata/script.rs#L236

### PR DESCRIPTION
**Pull request by jim4067**
Resolves #1247

### CODE REVIEW

**Comment by jim4067** [comment]
@apoelstra seems like I bit off more than I could chew. gonna have to leave this one.

**Comment by jim4067** [comment]
Thanks for the help, Andrew.
The suggestion for testing did work, but for the second one as pointed out in the issues, I think you need to have the implementation for the extension trait which would require a macro similar to the `core` ones which you suggested. 

That's where I got lost.

**Comment by apoelstra** [comment]
Nice! If we merge #1608 then we'll be able to remove the `allow(unused_imports)`.

Will ACK once my local CI passes.

**Review by apoelstra — DISMISSED** [review]
ACK 846c1d94bdee8d4d1d09ce18337ac2e8eea0bc21

**Comment by apoelstra** [comment]
@jim4067 you can't remove the attribute now, only if #1608 were to be merged.

**Comment by jim4067** [comment]
thanks @apoelstra, 

let me revert those changes.

File: internals/src/num/mod.rs [hunk 1]
```diff
@@ -0,0 +1,23 @@
...
+    /// the unsigned integer type
+    type Unsigned;
+
+    ///use this to find unsigned absolute if rust version less that 1.51
+    #[cfg(not(rust_v_1_51))]
+    fn unsigned_abs(self) -> Self::Unsigned;
+}
+
+impl IntExt for i64 {
+    type Unsigned = i64;
```
Comment (tcharding) [inline internals/src/num/mod.rs:14]: This is signed, should be `u64`, right?

File: internals/src/num/mod.rs [hunk 2]
```diff
@@ -0,0 +1,23 @@
...
+
+    fn unsigned_abs(self) -> Self::Unsigned {
+        if self < 0 {
+            -self
+        } else {
+            self
```
Comment (tcharding) [inline internals/src/num/mod.rs:20]: And you'll need casts here.

File: internals/src/num/mod.rs (hunk 1 above)
Comment (apoelstra) [reply internals/src/num/mod.rs:14]: Heh, derp, good catch.

Kinda interesting that the code works either way.

Comment (jim4067) [reply internals/src/num/mod.rs:14]: thanks. Wasn't sure if I should have used casting.

File: internals/src/num/mod.rs [hunk 3]
```diff
@@ -0,0 +1,23 @@
...
+pub trait IntExt {
+    /// the unsigned integer type
+    type Unsigned;
+
+    ///use this to find unsigned absolute if rust version less that 1.51
+    #[cfg(not(rust_v_1_51))]
+    fn unsigned_abs(self) -> Self::Unsigned;
+}
+
+impl IntExt for i64 {
```
Comment (Kixunil) [inline internals/src/num/mod.rs:13]: It might be useful to implement this for other types using a macro.

File: internals/src/num/mod.rs [hunk 4]
```diff
@@ -0,0 +1,23 @@
...
+    type Unsigned = u64;
+
+    fn unsigned_abs(self) -> Self::Unsigned {
```
Comment (Kixunil) [inline internals/src/num/mod.rs:16]: Needs a feature gate too.

File: internals/src/num/mod.rs [hunk 5]
```diff
@@ -0,0 +1,23 @@
...
+        if self < 0 {
+            -self as u64
+        } else {
+            self as u64
+        }
```
Comment (Kixunil) [inline internals/src/num/mod.rs:21]: I'm not sure if this is better than what's in `std` but I guess the optimizer will see it anyway.

**Review by Kixunil — COMMENTED** [review]
I remember we're using `unsigned_abs` in other places such as `amount`, perhaps include those as well.

File: internals/src/num/mod.rs (hunk 3 above)
Comment (apoelstra) [reply internals/src/num/mod.rs:13]: Well, it's a private trait and we only use it once.

File: internals/src/num/mod.rs (hunk 4 above)
Comment (apoelstra) [reply internals/src/num/mod.rs:16]: Ouch, why didn't CI catch this?

File: internals/src/num/mod.rs (hunk 3 above)
Comment (Kixunil) [reply internals/src/num/mod.rs:13]: I remember we had other uses, I don't remember which types. Maybe all of them are `i64`. :man_shrugging:

File: internals/src/num/mod.rs (hunk 4 above)
Comment (Kixunil) [reply internals/src/num/mod.rs:16]: WTF, that's really weird.

**Comment by apoelstra** [comment]
Also, @jim4067, since this discussion started we **did** merge #1608, so now you can remove the `#[allow(unused_imports)]`.

File: internals/src/num/mod.rs (hunk 4 above)
Comment (apoelstra) [reply internals/src/num/mod.rs:16]: Ok, prior to #1608, `rust_v_1_53` was a *feature flag* not a cfg parameter, so the gate was incorrect, and `not(rust_v_1_53)` would have always been true. On Rust 1.53 this *would've* caused a warning, but this PR suppressed it, something we mistakenly thought was needed for the case that people compile on 1.53 without the feature flag on.

After #1608 this would start causing compilation errors on 1.51 and above.... **except** that the flag has always been rust_v_1_**53** while this PR uses rust_v_1_**51**.

So, multiple mistakes and multiple review failures there. Oops.

Comment (Kixunil) [reply internals/src/num/mod.rs:16]: 51 is correct since that's the version the method was added in, we just need to add it into `build.rs`.

File: internals/src/num/mod.rs (hunk 5 above)
Comment (tcharding) [reply internals/src/num/mod.rs:21]: Ah bloody hell, just spent five minutes reading all the `abs`, `wrapping_abs`, `unsigned_abs` in the stdlib - I guess doing integer types correctly is hard. 

I think we should do what stdlib does and use 
```rust
pub fn unsigned_abs(x: i8) -> u8 {
    x.wrapping_abs() as u8
}
```
Call chain for input -128 : `wrapping_abs` -> `is_negative` -> `wrapping_neg` -> `wrapping_sub`

All available in our MSRV

phew!

Sorry for not investigating fully when this work started.

File: internals/src/num/mod.rs (hunk 3 above)
Comment (tcharding) [reply internals/src/num/mod.rs:13]: How about we let @jim4067 work this in as a single imp and then I"ll macro-ize it once merged with all the other integer types? @jim4067 does that suit you?

File: internals/src/num/mod.rs (hunk 5 above)
Comment (apoelstra) [reply internals/src/num/mod.rs:21]: I've gotta say, this is possibly the worst first issue @jim4067 could've taken up -- sorry!! It has turned out to be 10x as complicated as any of us first expected.

File: internals/src/num/mod.rs (hunk 3 above)
Comment (jim4067) [reply internals/src/num/mod.rs:13]: @tcharding, sounds good.

File: internals/src/num/mod.rs (hunk 5 above)
Comment (jim4067) [reply internals/src/num/mod.rs:21]: @apoelstra its okay. I consider this a great learning experience.
