### ISSUE TITLE
0.32.x - Backporting consensus-encoding requires MSRV of 1.65.0

### ISSUE THREAD

**Issue by jamillambert** [rust-bitcoin/rust-bitcoin#6068]
I am working on backporting consensus-encoding to 0.32.x but it looks like it requires an MSRV of 1.65.0.

Should we do a new release that is just changing the MSRV, which should be trivial to upgrade to, or at least a definite easy to see blocker. And then consensus-encoding can be added as a point release?

Related discussion #6010

Edit: It will require 1.74.0 due to `bitcoin-internals` 0.5.0

**Comment by apoelstra** [comment]
We can use `cfg(rust_v_1_65)` to gate the new impls on Rust 1.65 being available.

I think all our actual downstream users (I checked bdk, ldk and rust-elements) have a higher MSRV and things will just work. Meanwhile, we won't break projects like rust-miniscript who have a lower MSRV. Naturally, they won't be able to use the new impls until they have the new compiler.

**Comment by jamillambert** [comment]
I haven't been able to get this to work. Gating the code is fine, the issue is older Cargo tries to resolve optional manifest dependencies up front, and it fails on `bitcoin-consensus-encoding`’s `bitcoin-internals` 0.5.0 dependency. I am switching to working on a version with an MSRV of 1.74 in the meantime.

**Comment by apoelstra** [comment]
> fails on `bitcoin-consensus-encoding`’s `bitcoin-internals` 0.5.0 dependency

In what way? Is it the `rust-version` setting on `bitcoin-internals` or the lockfile version? Probably either one can be "fixed" in a 0.5.1.

**Comment by jamillambert** [comment]
To be honest I didn't understand the issue, so I got AI to explain it to me:

"The issue is that bitcoin-internals >= 0.4.1 is published with crates.io index schema v2 (`"v":2, "features2": ...`), because it uses weak dependency feature syntax like `hex?/alloc`". And "old Cargo cannot read the newer crates.io index entry format used by 0.4.1+"

So the problem could be fixed by changing the internals `Cargo.toml` to not use the newer syntax of `hex?/alloc`. I'll test this locally and see if I can then get it all to work before I open a PR for internals.

**Comment by apoelstra** [comment]
Ahh, interesting (and frustrating).

I think we need to replace the `?` syntax with explicit `hex-std` and `hex-alloc` features. This is ugly but there's only two of them, and it's an internal-only crate (so while this will require an `internals 0.6` we can depend on that in `bitcoin-consensus-encoding` without a major version bump), and if this is the only thing blocking adding the consensus-encoding traits to bitcoin 0.32 .... we gotta do it.

Alternately we could try to just remove `hex?/alloc` and `hex?/std`. Maybe we're not actually using std/alloc in hex? Will still require internals 0.6.

**Comment by tcharding** [comment]
Looks like the `hex` feature is only used for `SerializeBytesAsHex` which is used in exactly one place `primitives/src/witness.rs` we could inline it.

Since we are waiting on `consensus-encoding` to relase the whole stack its a good time to do `internals 0.6.0` - our six month thing is totally dead though ...

IIRC we tried not to do a breaking release of `internals` at some stage recently so I'd hazard a guess that there are other breaking changes we can do at the same time. Especially with the new `include/` thing. Perhaps @mpbagot knows off the top of his head without me looking?

**Comment by mpbagot** [comment]
Just checked the git diff. The only changes since v0.5.0 are dropping the `compact_size` module, deprecating the `transparent_newtype` macro and adding the api files.

Last release commit was c1a2e97c19e4d54d793ff1796876f41fe3acf37e and I checked using:
```bash
git diff c1a2e97c19e4d54d793ff1796876f41fe3acf37e internals/src
```
on `master`.
If we're happy to break things and have a bit of time, we could move more of the macros into `include` files like you mentioned in #5596

**Comment by apoelstra** [comment]
I'd prefer to just move quickly and release a new version of `internals` immediately. It's reasonably quick and easy to do it again later.

**Comment by tcharding** [comment]
Is it worth abusing semver and just releasing `0.4.1` with breaking changes in it? Since we are the only consumers. I'm concerned that we later do something in `0.6` that breaks the `0.32` build because we don't test against it.

**Comment by apoelstra** [comment]
>Is it worth abusing semver and just releasing 0.4.1 with breaking changes in it? 

Yeah, if the breaking changes don't break our own code I think it's fine. But I don't know what you're proposing here. The problems we're having are with 0.5.x, not 0.4.x, and the only dependents on 0.5.x are unreleased so there's no gain from doing a minor version rather than a major one.

**Comment by tcharding** [comment]
ooph because `consenus_encoding` depends on `internals 0.5` - face palm.

Can we yank `internals 0.5` and remove the hex dependency all together from 0.6 - then I'll be calm and happy.

**Comment by Kixunil** [comment]
Huh? Wasn't previous MSRV 1.63? Weak dependencies were stabilized in 1.60.

Weak dependencies solved some really painful issues, so I'd rather not drop them. Raising MSRV to 1.60+ seems perfectly fine to me.

**Comment by apoelstra** [comment]
>Raising MSRV to 1.60+ seems perfectly fine to me.

We are not going to raise the MSRV in a point release. At the very least this will break CI for all our downstream users.

> Can we yank `internals 0.5` and remove the hex dependency all together from 0.6 - then I'll be calm and happy.

Sure, we can do this, though I don't see the point in yanking 0.5 if nothing is even using it 🤷

**Comment by tcharding** [comment]
Yeah you are correct yanking achieves nothing.

**Comment by Kixunil** [comment]
> At the very least this will break CI for all our downstream users.

You mean all that didn't update to 1.60+ yet AND are NOT pinning their CI.

Anyway, if you want to release crippled versions of old crates I'm not going to care much, if at all.

**Comment by apoelstra** [comment]
Okay, so I've gone through the series of issues with `consensus-encoding` and MSRV:

* The "easy" one is that `internals 0.5.0` has a hex dep, uses `dep:` syntax, and uses `?` syntax. We can remove these, but then...
* ...but then we have `rust-version = "1.74.0" there. We can just drop it to "1.56.1" but cargo 1.56.1 insists on actually building the crate even if it's not used, and there are several compilation errors, some of which are easier than others to deal with
* ...for example, in build.rs we expect cargo to set the `CARGO_PKG_RUST_VERSION` envvar but apparently in 1.56.1 it doesn't; every other issue is related to constfns, but some like `trait bounds other than `Sized` on const fn parameters are unstable` look pretty hard to deal with.

I tried fixing a couple of these but ultimately there's little point, since even if we can make `internals` friendly to 1.56.1, or even remove the `internals` dep entirely, it `consensus-encoding` itself won't build on 1.56.1 due to its use of GATs.

What we really want is to have the `bitcoin-consensus-encoding` be conditioned on the current compiler version. But AFAICT cargo won't let us do this.

**Comment by apoelstra** [comment]
I am leaning toward Kix being right that we should just bump the MSRV in a minor version, trust downstream users to have pins or a more liberal MSRV, and be done with it. We maybe should reduce the MSRV of consensus-encoding to the minimum we can get away with though.

Let me try some more things though first.

**Comment by tcharding** [comment]
Am I understanding correctly we are trying to find the correct trade off between

1. Munge 0.32.x, `consensus_encoding`, `internals` and whatever else so we can depend on `consensus_encoding` so downstream kind of gets in for free
2. Release 0.35, done totally correctly, but be a PITA for downstream

**Comment by apoelstra** [comment]
Yes, though "but be a PITA for downstream" is an understatement. It means that no types will simultaneously be compatible with 0.32.x and support the consensus-encoding traits.

**Comment by tcharding** [comment]
Please see: #6126

**Comment by yancyribbens** [comment]
I haven't been following this super close, although it feels unfortunate to need to bump MSRV as part of a patch release.  I can't help but wonder, if 0.32.x was just maintained as 1.x.x, then there would be the minor version number to play with as well instead of just the patch version.

**Comment by tcharding** [comment]
We have a minor version, in pre-1.0 crates its the 'patch' number. It is still incorrect to bump the MSRV in a minor version.

>  if 0.32.x was just maintained as 1.x.x

`rust-bitcoin 0.32.x` _is_ `1.0.0` - YOLO. \me moves to the woods and never touches a computer again.

**Comment by yancyribbens** [comment]
> rust-bitcoin 0.32.x is 1.0.0 - YOLO. \me moves to the woods and never touches a computer again.

I mean, all the work that's been done for a "1.0" would be a "2.0".  I'm not advocating for throwing out the years of work done on this project.

**Comment by jamillambert** [comment]
Solved by #6126
