### PR TITLE
Add serde impls for FilterHash and FilterHeader

### LINKED ISSUE #5691: `FilterHash` does not implement `serde` traits
When we moved the hash types from `bip158` to `p2p` we lost the `serde` traits.

(Issue relates to all the hash types that we moved.)

### PR DESCRIPTION
**Pull request by busayo-OD**
This PR adds serde impls for `FilterHash` and `FilterHeader` that were lost whenthese types were moved from bitcoin/src/bip158.rs` to `p2p` in #5387.

Closes #5691

### CODE REVIEW

**Comment by tcharding** [comment]
Thanks for the contribution! FYI the CI fail is unrelated, this will need rebasing after #5764 goes in.

Note to reviewers, see #5777. Also I don't understand why `just ulf` is not adding `serde` dep to `Cargo-recent.lock`?

**Comment by busayo-OD** [comment]
> Thanks for the contribution! FYI the CI fail is unrelated, this will need rebasing after #5764 goes in.
> 
> Note to reviewers, see #5777. Also I don't understand why `just ulf` is not adding `serde` dep to `Cargo-recent.lock`?

Thanks for the review! I'll rebase once that merges.

**Comment by tcharding** [comment]
Can be rebased now, #5764 is in.

**Comment by busayo-OD** [comment]
> Can be rebased now, #5764 is in.

Thanks for the update! I've rebased.

**Comment by apoelstra** [comment]
Please squash the lockfile update into the change that requires it.

**Comment by tcharding** [comment]
ooo, my bad. Twice today I mixed up 'API updates' and 'lockfile updates'.

**Comment by nyonson** [comment]
Any concerns with adding `serde` to `p2p`? I can't really think of a reason not to other than keep things simple. And looks like we gotta here.

In any case, we should add the optional `serde` feature to the feature flag matrix test settings at some point: https://github.com/rust-bitcoin/rust-bitcoin/blob/master/p2p/rbmt.toml#L10-L14

**Comment by busayo-OD** [comment]
> Any concerns with adding `serde` to `p2p`? I can't really think of a reason not to other than keep things simple. And looks like we gotta here.
> 
> In any case, we should add the optional `serde` feature to the feature flag matrix test settings at some point: https://github.com/rust-bitcoin/rust-bitcoin/blob/master/p2p/rbmt.toml#L10-L14

Thanks for the review! Should I include that in this PR?

**Comment by nyonson** [comment]
Wouldn't hurt! You also still have to squash the lockfile commit into the first one.

**Comment by rustaceanrob** [comment]
> Any concerns with adding serde to p2p? 

Along that vein, no concern given that it's an optional dependency, but shouldn't we whole-sale implement these traits for all the types that could use them? Who would need `serde` implementations for `FilterHash` and nothing else?

**Comment by tcharding** [comment]
> Along that vein, no concern given that it's an optional dependency, but shouldn't we whole-sale implement these traits for all the types that could use them? 

If so I rekon it can be a follow up because it would make first time contribution a lot more difficult.

> Who would need serde implementations for FilterHash and nothing else?

`corepc-types` doesn't use anything else out of the `p2p` crate except `FilterHash`.

**Comment by rustaceanrob** [comment]
ACK 5e968d577b10c87a3cab79a8bbda9a27c1dbfb4a
