### PR TITLE
use lambda instead of a hash map to find spent outputs

### PR DESCRIPTION
**Pull request by tamasblummer**
Avoid allocation of a HashMap that is just one possible implementation of finding TxOut for an OutPoint. Do not require retrieval of the entire transaction, just the output that is spent.

### CODE REVIEW

File: src/blockdata/transaction.rs [hunk 1]
```diff
@@ -407,17 +406,14 @@ impl Transaction {
 
     #[cfg(feature="bitcoinconsensus")]
     /// Verify that this transaction is able to spend some outputs of spent transactions
-    pub fn verify(&self, spent: &HashMap<sha256d::Hash, Transaction>) -> Result<(), script::Error> {
+    pub fn verify<S>(&self, spent: S) -> Result<(), script::Error>
+        where S: Fn(&OutPoint) -> Option<TxOut> {
```
Comment (apoelstra) [inline src/blockdata/transaction.rs]: Can we use `FnOnce` rather than `Fn`?

**Comment by apoelstra** [comment]
concept ACK

File: src/blockdata/transaction.rs (hunk 1 above)
Comment (tamasblummer) [reply src/blockdata/transaction.rs]: the function is called in a loop, I think that is against the rule of FnOnce that it should only be called once. I could make it called once only to resolve all input, but that would complicate the implementation, I do not think it is worth it.

Comment (apoelstra) [reply src/blockdata/transaction.rs]: Oh, oops, I missed the loop. `FnMut` then? You may need to call the closure with `&mut spent` rather than just `spent`.

I don't actually know in what contexts `FnMut` won't work and you'd need `Fn`.

**Comment by apoelstra** [comment]
BTW you can borrow rather than cloning.

File: src/blockdata/transaction.rs (hunk 1 above)
Comment (tamasblummer) [reply src/blockdata/transaction.rs]: While I was thinking about why one would use FnMut I recognized that this is the best place to catch transactions that try to re-use (double spend) the same input. The resolver should update its state so it is not returning the same txout twice. Also added test for this

**Comment by tamasblummer** [comment]
My last commit eliminates the clone too. See comment https://github.com/rust-bitcoin/rust-bitcoin/pull/319#discussion_r316344696

File: src/blockdata/transaction.rs [hunk 2]
```diff
@@ -405,12 +405,13 @@ impl Transaction {
     }
 
     #[cfg(feature="bitcoinconsensus")]
-    /// Verify that this transaction is able to spend some outputs of spent transactions
-    pub fn verify<S>(&self, spent: S) -> Result<(), script::Error>
-        where S: Fn(&OutPoint) -> Option<TxOut> {
+    /// Verify that this transaction is able to spend its inputs
+    /// The lambda spent should not return the same TxOut twice!
+    pub fn verify<S>(&self, mut spent: S) -> Result<(), script::Error>
+        where S: FnMut(&OutPoint) -> Option<TxOut> {
```
Comment (dongcarl) [inline src/blockdata/transaction.rs]: I might be wrong but perhaps we can have `S` return `Option<&TxOut>` instead?

File: src/blockdata/transaction.rs [hunk 3]
```diff
@@ -1126,19 +1127,36 @@ mod tests {
...
+        let mut spent2 = spent.clone();
+        let mut spent3 = spent.clone();
 
-        let resolver = |point: &OutPoint| {
-            if let Some(tx) = spent.get(&point.txid) {
+        spending.verify(|point: &OutPoint| {
+            if let Some(tx) = spent.remove(&point.txid) {
                 return tx.output.get(point.vout as usize).cloned();
             }
             None
```
Comment (dongcarl) [inline src/blockdata/transaction.rs]: This and other following tests can be simplified to something like: 
```
spent.remove(point.txid).map(|tx| tx.output.get(point.vout as usize))
```

File: src/blockdata/transaction.rs (hunk 2 above)
Comment (tamasblummer) [reply src/blockdata/transaction.rs]: requiring to return reference gets one easily into a lifetime hell in my experience. Why not instead take ownership of a small data object.

File: src/blockdata/transaction.rs (hunk 3 above)
Comment (tamasblummer) [reply src/blockdata/transaction.rs]: spent.remove(&point.txid).and_then(|tx| tx.output.get(point.vout as usize).cloned()) would work as otherwise it would be Option<Option<TxOut>> also tried to return reference here end got into trouble, not worth it. Since tests are readable I leave as is.

File: src/blockdata/transaction.rs (hunk 2 above)
Comment (apoelstra) [reply src/blockdata/transaction.rs]: Yeah, there aren't any good options for the lifetime to put on an `&TxOut` here. (The only semantically sensible thing I can think of is to introduce a new lifetime and bound `S` by it; this would correspond to the lifetime of the closed-over data in `spent`. But with `FnMut` this will become very painful very quickly; and if we instead require `Fn` then that restricts the generality of the function (and also, chances are users will still run into trouble with rustc)).

Comment (apoelstra) [reply src/blockdata/transaction.rs]: To be clear, I think if rustc was better at dealing with references in closure types I'd agree with Carl here. But it's not.

Comment (dongcarl) [reply src/blockdata/transaction.rs]: @apoelstra @tamasblummer Just for my own edification, why would this require a lifetime? I tried just replacing the return type with `Option<&TxOut>` here, and it compiles and runs fine: https://github.com/rust-bitcoin/rust-bitcoin/compare/38f1775c360c9e8056dc095b6d193fb0fec66b05...dongcarl:2019-08-closure-ref-edification

It's even being used without weird lifetimes in the tests. I'm probably missing something so I'd like to know.

Comment (elichai) [reply src/blockdata/transaction.rs]: with latest stable you can probably get away without lifetimes.
Try running this code on 1.22.0

Comment (dongcarl) [reply src/blockdata/transaction.rs]: @elichai it works fine on `1.22.0`

Comment (elichai) [reply src/blockdata/transaction.rs]: Cool. didn't know lifetime elisions were already pretty good at 1.22

Comment (tamasblummer) [reply src/blockdata/transaction.rs]: Just because you can compile the interface does not mean it is easy to use.
Let's do the naive change:
```
 pub fn verify<S>(&self, mut spent: S) -> Result<(), script::Error>
        where S: FnMut(&OutPoint) -> Option<&TxOut> {
```
and then try to use it as:
```
 spending.verify(|point: &OutPoint| {
            spent.remove(&point.txid).and_then(|tx| tx.output.get(point.vout as usize))
        }).unwrap();
```
results in 
```
     |             spent.remove(&point.txid).and_then(|tx| tx.output.get(point.vout as usize))
     |                                                     ---------^^^^^^^^^^^^^^^^^^^^^^^^^
     |                                                     |
     |                                                     returns a value referencing data owned by the current function
     |                                                     `tx.output` is borrowed here

error[E0515]: cannot return value referencing local data `tx.output`
```

Let me know if you have a solution also for the usage.

Comment (apoelstra) [reply src/blockdata/transaction.rs]: @dongcarl @elichai yes you need lifetimes. If you don't write them they are still there, and Rust will default to using the same lifetime for both `&OutPoint` and `&Output`. Can you describe any situation where that makes sense?

Comment (stevenroose) [reply src/blockdata/transaction.rs]: I think the lifetime problem is because it's an `FnMut`. And that in turn is because of this comment: 

> The lambda spent should not return the same TxOut twice!

I personally think it's better if the `spent` closure would be renamed `get_utxo`, becomes `Fn(&'a OutPoint) -> Option<&'b TxOut>` (whether or not the lifetimes are needed I don't know, just indicating that they are different ones) and that the method keeps track of double spending itself.

That way, in @tamasblummer 's example, you don't need to remove the tx from his collection. One can always just inspect a certain collection and return a reference to the `TxOut`. I also think it would be a lot more efficient if the closure would not mutate data. Keeping track of double spending inside the `verify` transaction is also trivial.

Comment (stevenroose) [reply src/blockdata/transaction.rs]: Since this is already merged, I made a proposal for a slight improvement. Feel free to disregard it: https://github.com/rust-bitcoin/rust-bitcoin/pull/327
