### PR TITLE
Add weight utilities to `TxIn` and `TxOut`

### PR DESCRIPTION
**Pull request by danielabrozzoni**
- Add `segwit_weight` and `legacy_weight` methods to `TxIn`
- Add `weight` method to `TxOut`

### CODE REVIEW

**Comment by apoelstra** [comment]
Heads up (though CI will flag I'm sure) that this doesn't compile with 1.41.0:
```
   Compiling bitcoin v0.29.0 (/tmp/tmpiw57dv_s/bitcoin)
error[E0277]: `[(bool, &str); 6]` is not an iterator
    --> bitcoin/src/blockdata/transaction.rs:1555:32
     |
1555 |         for (is_segwit, tx) in txs {
     |                                ^^^ borrow the array with `&` or call `.iter()` on it to iterate over it
     |
     = help: the trait `std::iter::Iterator` is not implemented for `[(bool, &str); 6]`
     = note: arrays are not iterators, but slices like the following are: `&[1, 2, 3]`
     = note: required by `std::iter::IntoIterator::into_iter`

error[E0277]: the size for values of type `str` cannot be known at compilation time
    --> bitcoin/src/blockdata/transaction.rs:1561:61
     |
1561 |             let tx: Transaction = deserialize(Vec::from_hex(&tx).unwrap().as_slice()).unwrap();
     |                                                             ^^^ doesn't have a size known at compile-time
     |
     = help: the trait `std::marker::Sized` is not implemented for `str`
     = note: to learn more, visit <https://doc.rust-lang.org/book/ch19-04-advanced-types.html#dynamically-sized-types-and-the-sized-trait>
     = note: all local variables must have a statically known size
     = help: unsized locals are gated as an unstable feature
```
otherwise d758074a8f583cd722f8b02deb0958789ea4a97f look good.

**Comment by sanket1729** [comment]
Pardon my ignorance, but what is the use of `legacy_weight`? Is `segwit_weight` not the only weight we should care about?  

Is this about the one byte flag whether the tx contains witnesses or not?

**Comment by Kixunil** [comment]
Do we know someone who actually uses it? If not, I'd just drop it for now and add when someone asks.

File: bitcoin/src/blockdata/transaction.rs [hunk 1]
```diff
@@ -225,6 +225,28 @@ impl TxIn {
...
+        // We then multiply by 4 to convert to WU
+        (36 + VarInt(script_sig_size as u64).len() + script_sig_size + 4) * 4
+    }
+
+    /// The weight of the TxIn when it's included in a segwit transaction (i.e., a transcation
+    /// having at least one segwit input).
+    ///
+    /// This always takes into account the witness, even when empty, in which
+    /// case 1WU for the witness length varint (`00`) is included.
+    pub fn segwit_weight(&self) -> usize {
```
Comment (Kixunil) [inline bitcoin/src/blockdata/transaction.rs:247]: If this is not called `min_segwit_weight` (why?) it should have a well-visible warning that it doesn't account for varint changing so naive sum wouldn't work.

Also I recently found out that Core has `FeeRate` type but we don't which feels ridiculous. I obviously don't ask you to add it just a note.

**Comment by danielabrozzoni** [comment]
> Heads up (though CI will flag I'm sure) that this doesn't compile with 1.41.0:

Updated, thanks!

> Do we know someone who actually uses it? If not, I'd just drop it for now and add when someone asks.

This is needed for https://github.com/rust-bitcoin/rust-miniscript/pull/476 :)

>  it's the weird reported to pre-segwit nodes ... which, okay, there's an argument that we don't really care about pre-segwit nodes 6 years after Segwit activation, but that's the value.

Yes, and also the correct weight of non-segwit inputs when included in non-segwit transactions, since the `segwit_weight` always includes (at least) 1WU for the witness length, even when the witness is empty

**Review by apoelstra — DISMISSED** [review]
ACK a3ca7e8e51f8dc00eb41803b1e4be82310ca5a78

File: bitcoin/src/blockdata/transaction.rs [hunk 2]
```diff
@@ -1492,6 +1525,50 @@ mod tests {
...
+                // one legacy input (P2PKH)
+                (false, "0100000001c336895d9fa674f8b1e294fd006b1ac8266939161600e04788c515089991b50a030000006a47304402204213769e823984b31dcb7104f2c99279e74249eacd4246dabcf2575f85b365aa02200c3ee89c84344ae326b637101a92448664a8d39a009c8ad5d147c752cbe112970121028b1b44b4903c9103c07d5a23e3c7cf7aeb0ba45ddbd2cfdce469ab197381f195fdffffff040000000000000000536a4c5058325bb7b7251cf9e36cac35d691bd37431eeea426d42cbdecca4db20794f9a4030e6cb5211fabf887642bcad98c9994430facb712da8ae5e12c9ae5ff314127d33665000bb26c0067000bb0bf00322a50c300000000000017a9145ca04fdc0a6d2f4e3f67cfeb97e438bb6287725f8750c30000000000001976a91423086a767de0143523e818d4273ddfe6d9e4bbcc88acc8465003000000001976a914c95cbacc416f757c65c942f9b6b8a20038b9b12988ac00000000"),
+            ];
+
+        let empty_transaction_size = Transaction {
+            version: 0,
+            lock_time: absolute::PackedLockTime(0),
```
Comment (apoelstra) [inline bitcoin/src/blockdata/transaction.rs:1549]: Since #1330 this should be `absolute::LockTime::ZERO`.

File: bitcoin/src/blockdata/transaction.rs (hunk 1 above)
Comment (danielabrozzoni) [reply bitcoin/src/blockdata/transaction.rs:257]: Right! I just added a warning to the docs, let me know how you feel about it :)

```diff
+    /// Keep in mind that when adding a TxIn to a transaction, the total weight of the transaction
+    /// might increase more than `TxIn::segwit_weight`. This happens when:
+    /// - the new input added causes the input length `VarInt` to increase its encoding length
+    /// - the new input is the first segwit input added - this will add an additional 2WU to the
+    /// transaction weight to take into account the segwit marker
```

**Comment by apoelstra** [comment]
The new docs look great. Though I really wish there were a way to compute transaction weight without these footguns :/. Maybe we could have a method on `Psbt` that could more-reliably predict weight.

**Review by apoelstra — APPROVED** [review]
ACK 6d51e9255b969e142d0fae6d4cf3fcdd8cfae0cc

**Review by Kixunil — COMMENTED** [review]
The doc looks great.

I guess you missed my question about naming. I think naming it `min_legacy_weight`, `min_segwit_weight` and `min_weight` would make the potential foot gun more visible *in the code*. Is there some reason why the `min_` prefix is undesirable?

**Comment by apoelstra** [comment]
+1 to adding _min to the names -- sorry, I forgot about this suggestion too.

**Comment by danielabrozzoni** [comment]
> I guess you missed my question about naming. I think naming it min_legacy_weight, min_segwit_weight and min_weight would make the potential foot gun more visible in the code. Is there some reason why the min_ prefix is undesirable?

Ops, sorry!
I do see your point about warning users, but I'm not sure if that's the best way of accomplishing it. I consider the segwit marker and the txin/txout varint length to be *outside* the txins/txouts themselves, so I think that the weight we give back is the exact weight of the object, not the minimum one.

**Comment by RCasatta** [comment]
I don't think the `min_` makes a lot of sense since the varint and the markers are outside of the `TxIn` .

For the same reasoning, should we use `Transaction::min_weight()` because if serialized in a block could change the varint of the number of transactions in the block?

**Comment by apoelstra** [comment]
Yeah, these are good arguments. `min_` does sound like the weight of the actual input could potentially be larger, or that it can't be computed exactly.

**Comment by Kixunil** [comment]
Yeah, good points.

**Comment by danielabrozzoni** [comment]
Sure, I'm afk now, but I'll fix asap!

-------- Original Message --------

File: bitcoin/src/blockdata/transaction.rs [hunk 3]
```diff
@@ -225,6 +225,38 @@ impl TxIn {
...
+    /// having at least one segwit input).
+    ///
+    /// This always takes into account the witness, even when empty, in which
+    /// case 1WU for the witness length varint (`00`) is included.
+    ///
+    /// Keep in mind that when adding a TxIn to a transaction, the total weight of the transaction
+    /// might increase more than `TxIn::segwit_weight`. This happens when:
+    /// - the new input added causes the input length `VarInt` to increase its encoding length
+    /// - the new input is the first segwit input added - this will add an additional 2WU to the
+    /// transaction weight to take into account the segwit marker
```
[the remark this answers is not in the document]
Comment (danielabrozzoni) [reply bitcoin/src/blockdata/transaction.rs:256]: Btw, `cargo doc` renders this just fine:

Selection_126

But I agree that it should be fixed for the people reading the docs in the files itself, I'll do it as a part of #828. Do you think there are enough typos to fix it immediately, or should I wait a bit longer?
