### PR TITLE
Add bech32 support

### LINKED ISSUE #53: Add bech32 addresses to address code.
Could probably rely on https://github.com/clarkmoody/rust-bech32 for the bech32-parsing side of things (yay not even any deps in it!).

### PR DESCRIPTION
**Pull request by apoelstra**
Fixes #53

### CODE REVIEW

**Comment by apoelstra** [comment]
cc @TheBlueMatt

**Comment by clarkmoody** [comment]
Did you mean Fixes #53 ?

**Comment by apoelstra** [comment]
Lol yes, thanks

File: src/util/address.rs [hunk 1]
```diff
@@ -18,125 +18,166 @@
...
+                let mut prefixed = [0; 21];
+                prefixed[0] = match self.network {
+                    Network::Bitcoin => 5,
+                    Network::Testnet => 196,
+                };
+                prefixed[1..].copy_from_slice(&hash[..]);
+                base58::check_encode_slice(&prefixed[..])
+            }
+            Payload::WitnessProgram(ref witprog) => {
+                witprog.to_address().unwrap()
```
Comment (TheBlueMatt) [inline src/util/address.rs]: This unwrap() can fail, probably should just fix upstream so taht you cant get a witprog that is invalid (ie a failing creation function).

File: src/util/address.rs [hunk 2]
```diff
@@ -15,129 +15,176 @@
...
-            hash: if compressed {
-                Hash160::from_data(&pk.serialize()[..])
-            } else {
-                Hash160::from_data(&pk.serialize_uncompressed()[..])
-            }
+            payload: Payload::PubkeyHash(
+                if compressed {
+                    Hash160::from_data(&pk.serialize()[..])
+                } else {
+                    Hash160::from_data(&pk.serialize_uncompressed()[..])
```
Comment (tamasblummer) [inline src/util/address.rs]: Should the library support uncompressed pubkey at all? This is legacy just like pay-to-pubkey that is also not supported as we hope it goes extinct.

File: src/util/address.rs (hunk 1 above)
Comment (apoelstra) [reply src/util/address.rs]: Good catch. Will PR upstream to hide internals.

File: src/util/bip32.rs [hunk 3]
```diff
@@ -337,33 +338,36 @@ impl ExtendedPubKey {
...
-            Network::Bitcoin => [0x04, 0x88, 0xAD, 0xE4],
-            Network::Testnet => [0x04, 0x35, 0x83, 0x94]
-        }.iter().cloned());
-        ret.push(self.depth as u8);
-        ret.extend(self.parent_fingerprint[..].iter().cloned());
+impl ToString for ExtendedPrivKey {
+    fn to_string(&self) -> String {
+        let mut ret = [0; 78];
+        ret[0..4].copy_from_slice(match self.network {
+            Network::Bitcoin => &[0x04, 0x88, 0xAD, 0xE4][..],
```
Comment (clarkmoody) [inline src/util/bip32.rs]: Would be nice to break these version bytes (and other constants elsewhere) into an external repo. Maybe not now, but soon?

File: src/util/bip32.rs [hunk 4]
```diff
@@ -337,33 +338,36 @@ impl ExtendedPubKey {
...
+            Network::Testnet => &[0x04, 0x35, 0x83, 0x94][..],
```
Comment (tamasblummer) [inline src/util/bip32.rs]: I get compile errors here on branch bech32:

 --> src/util/bip32.rs:345:61
    |
345 |             Network::Bitcoin => &[0x04, 0x88, 0xAD, 0xE4][..],
    |                                  ------------------------   ^ temporary value dropped here while still borrowed
    |                                  |
    |                                  temporary value created here
346 |             Network::Testnet => &[0x04, 0x35, 0x83, 0x94][..],
347 |         });
    |          - temporary value needs to live until here

error[E0597]: borrowed value does not live long enough
   --> src/util/bip32.rs:346:61
    |
346 |             Network::Testnet => &[0x04, 0x35, 0x83, 0x94][..],
    |                                  ------------------------   ^ temporary value dropped here while still borrowed
    |                                  |
    |                                  temporary value created here
347 |         });
    |          - temporary value needs to live until here

error[E0597]: borrowed value does not live long enough
   --> src/util/bip32.rs:403:63
    |
403 |             Network::Bitcoin => &[0x04u8, 0x88, 0xB2, 0x1E][..],
    |                                  --------------------------   ^ temporary value dropped here while still borrowed
    |                                  |
    |                                  temporary value created here
404 |             Network::Testnet => &[0x04u8, 0x35, 0x87, 0xCF][..],
405 |         });
    |          - temporary value needs to live until here

error[E0597]: borrowed value does not live long enough
   --> src/util/bip32.rs:404:63
    |
404 |             Network::Testnet => &[0x04u8, 0x35, 0x87, 0xCF][..],
    |                                  --------------------------   ^ temporary value dropped here while still borrowed
    |                                  |
    |                                  temporary value created here
405 |         });
    |          - temporary value needs to live until here

error: aborting due to 4 previous errors

Comment (tamasblummer) [reply src/util/bip32.rs]: running rustc 1.20 on osx

File: src/util/bip32.rs (hunk 3 above)
Comment (TheBlueMatt) [reply src/util/bip32.rs]: Does that really need to be an external repo? We could move the address parsing stuff into its own repo and expose these constants but having a repo for constants collection just seems like naval-gazing.

Comment (apoelstra) [reply src/util/bip32.rs]: Agreed. @TheBlueMatt thoughts? This would add a formal dependency to basically every Bitcoin lib but it would eliminate a bunch of constant-conversion code.

**Comment by apoelstra** [comment]
Blocked on https://github.com/rust-bitcoin/rust-bech32-bitcoin/pull/9 or something similar

File: src/util/bip32.rs (hunk 4 above)
Comment (apoelstra) [reply src/util/bip32.rs]: Thanks, works on rustc 1.24, I'll test with 1.20.

Comment (apoelstra) [reply src/util/bip32.rs]: Can reproduce. Will fix.

Comment (apoelstra) [reply src/util/bip32.rs]: Pushed fix which works back to 1.16 at least (though the bech32 dep does not because it uses implicit struct names, something clippy recommends even though it breaks backward compat).

File: src/util/address.rs (hunk 2 above)
Comment (apoelstra) [reply src/util/address.rs]: If somebody wanted to write code for pay-to-pubkey I'd support it actually...I encountered somebody with an old wallet not too long ago (in 2017) who had some pay-to-pub outputs in an old Electrum wallet, and I had to walk him through importing to Core because Electrum had dropped support for them.

Not that I feel too strongly about this ... I agree uncompressed keys suck.

**Comment by clarkmoody** [comment]
Merged [rust-bitcoin/rust-bech32-bitcoin#9](https://github.com/rust-bitcoin/rust-bech32-bitcoin/pull/9) and pushed `0.5.0` to Crates.io.

File: src/util/bip32.rs (hunk 3 above)
Comment (clarkmoody) [reply src/util/bip32.rs]: As it stands, there are some `hrp` constants defined in `rust-bech32-bitcoin` for multiple chains. One approach is to move those constants into this library's `constants` module, but that creates a circular dependency.

As written, this code works for Bitcoin only, and any additional chain support requires updating many places within the code.

Not that I want to support lots of altcoins, but the lightning effort gets very interesting in the cross-chain channels case.

The simplest way forward is including only the constants embedded in nice `enum`s, without classification code.

**Comment by apoelstra** [comment]
@clarkmoody  oops, I also need https://github.com/rust-bitcoin/rust-bech32-bitcoin/pull/10 :)

**Comment by clarkmoody** [comment]
@apoelstra 👍

**Comment by apoelstra** [comment]
@TheBlueMatt fixed `unwrap` issue

File: src/util/address.rs [hunk 5]
```diff
@@ -166,7 +213,7 @@ impl Privkey {
     /// Converts a private key to an address
```
Comment (tamasblummer) [inline src/util/address.rs]: PrivateKey should not be in this module. It should not be an afterthought of address. Compressed/uncompressed is not an attribute of Private key but that of PublicKey. This is not a stopper for this PR but needs clean up.
