### PR TITLE
Start crate smashing

### PR DESCRIPTION
**Pull request by tcharding**
I'm expecting this to take a few iterations. ~Not sure if this is wanted still as part of 0.28 release. I've taken it off draft because its _ready_ for review although clearly not ready for merge.~ I need input from others for this one, both opinions and also some technical things, primarily I cannot work out how to re-export `bitcoin_hashes` from `bitocoin-str` and get macros to work in Rust 1.29 (that should be the only CI failure), it builds locally with newer versions of Rust.

Make an attempt to start the crate smashing described in https://github.com/rust-bitcoin/rust-bitcoin/issues/550. This is a long thread and its not super easy to tease out what has consensus and what does not but this PR will try to do that. 

The stated aims of this work are:

- Reduce LOC count and compile times for downstream projects that do not need all of the code in `rust-bitcoin`.
- Assist in stabilising the codebase by having conservative code in separate crates from frequently changing code (includes assisting downstream users, and the wider Rust Bitcoin ecosystem, in being able to upgrade, easily and rapidly, the more stable crates).
- Make the codebase more closely follow principles of Clean Architecture (orphan rule aside).

At a high level this PR does:
- Create a workspace, move all the code int a crate called `bitcoin`
- Extract out a second crate called `bitcoin-str` (also referred to as `bitcoin-encoding` in the issue thread)

I've tried to only do changes required to make code build when extracting code into `bitcoin-str`.

`bitcoin-str` includes:

- Extracted base58 module
- Extracted endian module
- Re-export of extern bech32 crate
- Re-export of extern base64 crate
- Re-export of extern bitcoin_hashes crate as hashes
- Attempted to re-export `hashes::hex::*` from module `bitcoin_str::hex` for ergonomics

## Questions/TODOs

- Work out why Rust 1.29 cannot find macro re-exported in `bitcoin-str/src/hex.rs` (CI failure)?
- Same issue as above, but for using macros from `bitcoin_hashes` in `bitcoin`.
- What '10-20 lines of core code' does this post refer to? https://github.com/rust-bitcoin/rust-bitcoin/issues/550#issuecomment-761833959

### CODE REVIEW

**Comment by DON-MAC-256** [comment]
Any reason to switch to `bitcoin-str` from `bitcoin-encoding`, which seems to have rough consensus in #550?

**Comment by Kixunil** [comment]
Awesome, I just hit issues with `bitcoin` being a single crate (also related to `no_std`)

@DON-MAC-256 @apoelstra said he likes `bitcoin-str` more and nobody objected.

**Comment by Kixunil** [comment]
Thinking about this again wouldn't it be easier to start with separating-out primitives?

**Comment by tcharding** [comment]
> Thinking about this again wouldn't it be easier to start with separating-out primitives?

We have to start at the bottom, right?

**Comment by Kixunil** [comment]
Not sure what you consider bottom but thinking about it again:

 * isolated components (types/functions with no deps and nothing dependent) should be easiest but I don't know if we have many/any of those
 * separating entities should be most useful and reasonably easy. E.g. I need `Amount` a separate crate without the annoying `no-std` feature yesterday. :)
 * things that have dependencies are probably impossible to separate before their dependencies because they need to reference their dependencies and if they reference them within `bitcoin` crate they can't be re-exported in `bitcoin` crate (circular dependency)

**Comment by tcharding** [comment]
> Not sure what you consider bottom

I'm going to post a comment on the thread (#550) to try and keep the discussion in one place.

**Comment by tcharding** [comment]
> Not sure what you consider bottom

I took the bottom to be `bitcoin-str` (excluding external crates `bitcoin_hashes`, `bech32`, and `base64`). This is based primarily on the following to comments

- Andrew's comment: https://github.com/rust-bitcoin/rust-bitcoin/issues/550#issuecomment-759623446
- Your reply: https://github.com/rust-bitcoin/rust-bitcoin/issues/550#issuecomment-759671756

**Comment by Kixunil** [comment]
Actually, you're right. `bitcoin-str` must go first because we can't do Clean Architecture in Rust perfectly.

**Comment by Kixunil** [comment]
@tcharding IDK if you noticed that this was originally planned for version 0.30. Maybe it'll cause many rebases of this. However I would agree with change to get this in 0.29

**Comment by tcharding** [comment]
Oh I did not realize that, I thought it was wanted for `0.28`. I'll convert back to draft and put this on ice. Thanks for pointing that out.

File: bitcoin-str/Cargo.toml [hunk 1]
```diff
@@ -0,0 +1,41 @@
+[package]
+name = "bitcoin-str"
+version = "0.27.0"
```
Comment (thomaseizinger) [inline bitcoin-str/Cargo.toml:3]:
```suggestion
version = "0.1.0"
```

File: Cargo.toml [hunk 2]
```diff
@@ -1,60 +1,3 @@
...
-
-[[example]]
-name = "bip32"
-
-[[example]]
-name = "handshake"
-required-features = ["std"]
+[workspace]
+members = ["bitcoin", "bitcoin-str"]
+exclude = ["embedded", "fuzz"]
```
Comment (thomaseizinger) [inline Cargo.toml:3]: You can reduce the diff here by not moving the main crate into a subdirectory.

Regular crate manifests can also have a `[workspace]` table, meaning you can introduce `bitcoin-str` and move all the stuff in without touching anything in `bitcoin`.

File: bitcoin-str/Cargo.toml [hunk 3]
```diff
@@ -0,0 +1,41 @@
...
+std = ["bitcoin_hashes/std", "bech32/std"]
+no-std = ["core2/alloc", "bitcoin_hashes/alloc"]
+
+[package.metadata.docs.rs]
+features = [ "std", "secp-recovery", "base64", "rand", "use-serde", "bitcoinconsensus" ]
+rustdoc-args = ["--cfg", "docsrs"]
+
+[dependencies]
+bech32 = { version = "0.8.1", default-features = false }
+bitcoin_hashes = { version = "0.10.0", default-features = false }
```
Comment (thomaseizinger) [inline bitcoin-str/Cargo.toml:34]: Do we need the hashes as well or are we just taking `hex` from this? Would be nice to move `hex` into `bitcoin-str` and have `bitcoin-hashes` depend on `bitcoin-str`. AFAIK, `hex` only lives in `bitcoin-hashes` because `bitcoin-hashes` was already a leaf dependency.

Comment (apoelstra) [reply bitcoin-str/Cargo.toml:34]: concept ACK that dependency inversion.

Yes, the hex stuff was put into `bitcoin-hashes` purely because it was the smallest crate in the ecosystem. (I might've put hex into `bech32` if it'd been around at the time :P.)

File: Cargo.toml (hunk 2 above)
Comment (tcharding) [reply Cargo.toml:3]: Oh cool, I did not know that. Cheers man!

File: bitcoin-str/Cargo.toml (hunk 3 above)
Comment (tcharding) [reply bitcoin-str/Cargo.toml:34]: There are three functions in `base58` module that depend on hashing, e.g.
```
/// Obtain a string with the base58check encoding of a slice
/// (Tack the first 4 256-digits of the object's Bitcoin hash onto the end.)
pub fn check_encode_slice(data: &[u8]) -> String {
    let checksum = sha256d::Hash::hash(data);
    encode_iter(
        data.iter()
            .cloned()
            .chain(checksum[0..4].iter().cloned())
    )
}
```

Comment (Kixunil) [reply bitcoin-str/Cargo.toml:34]: Why we don't use the `hex` crate?

Comment (apoelstra) [reply bitcoin-str/Cargo.toml:34]: Because it's a 3rd-party dep and its functionality can be re-implemented in ten lines of code.

We have had problems in the past with these things (e.g. `base64` has caused us more trouble than it would've been to NIH hex *and* base64).

Comment (RCasatta) [reply bitcoin-str/Cargo.toml:34]: I [once suggested](https://github.com/Kixunil/loptos/issues/1#issuecomment-888896092) to use base64 feature from bitcoin crate and this random guy :) said `base64` was already in his crate as a transitive dep so he didn't want to add another base64 impl which is a reasonable point I think. 

Was the problem you mention about `base64` related to MSRV or something else?

Comment (apoelstra) [reply bitcoin-str/Cargo.toml:34]: Yes, related to MSRV, and a quite hostile response from the maintainer when we tried to fix it.

Comment (thomaseizinger) [reply bitcoin-str/Cargo.toml:34]: > I was hoping to convey that with the comment in `bitcoin-str/src/lib.rs`
> ```
> pub mod hex {
>     //! Re-exports hex de/serialization code from `bitcoin_hashes`.
>     //!
>     // There is a chicken and the egg problem with putting _all_ the en/decoding code in a single crate.
>     // Hashing cannot be separated totally from en/decoding because base58 -> hashing -> hex.
> ```
> 
> Or is there a way around this?

I can see the following options:

1. Make `bitcoin_hashes` _only_ do hashing with APIs that go from byte -> byte, removing the hex code from it
2. Move `bitcoin_hashes` into `bitcoin-str`. Not entirely correct but if we want to tightly couple them with hex then this issue would be resolved
3. Duplicate the hex-code across `bitcoin_hashes` and `bitcoin-str` and make it an implementation detail in `bitcoin_hashes`

(3) might overall be the cleanest approach regarding exposed APIs and crate structure. The hex code needed to parse and represent hashes is quite specific whereas if we want to expose hex encoding in `bitcoin-str` for general use then there are a lot more use-cases to support. I am thinking lazy iterators, stack-allocated encoding, etc.

Comment (apoelstra) [reply bitcoin-str/Cargo.toml:34]: I am leaning toward option (3), simply because hex is such a simple encoding that I'm not too bothered by its duplication.

Comment (Kixunil) [reply bitcoin-str/Cargo.toml:34]: 4. Move the code to a separate crate.
5. Discuss with the maintainer about MSRV and API stabilization - not everyone is hostile

I think 4 short term and 5 long-term would be nice but can also accept 3 since it's simple. (TBH, I also reimplemented it in one of my crates.)

Comment (dr-orlovsky) [reply bitcoin-str/Cargo.toml:34]: I already made a separate bitcoin_hex crate more than a year ago after we had a similar discussion, but its adoption here ended up nowhere and I archived it.

Comment (dr-orlovsky) [reply bitcoin-str/Cargo.toml:34]: Here the PR, closed it just three days ago: https://github.com/rust-bitcoin/bitcoin_hashes/pull/91

Comment (Kixunil) [reply bitcoin-str/Cargo.toml:34]: After reading [your argument](https://github.com/rust-bitcoin/rust-bitcoin/issues/467#issuecomment-687018559) I no longer feel comfortable with accepting option 3.

I believe we should really revive it. But could the crate be without "bitcoin" in its name or docs? I'd like it being neutral general purpose 1.36-compatible crate. `hex-compat` similarly to `base64-compat` sounds sensible.

Comment (dr-orlovsky) [reply bitcoin-str/Cargo.toml:34]: There is already `amplify_num` crate I made for this purpose,  when work on `bitcoin_hex` has stalled. I will be ok with moving it to this org and even renaming it.

Comment (apoelstra) [reply bitcoin-str/Cargo.toml:34]: I'm unconvinced that "changes will happen" to hex encoding code which require synchronized updates, but concept ACK having a separate hex-compat crate.

Agree that it shouldn't have `bitcoin` anywhere in the name.

I'm also OK in concept with talking to the `hex` maintainer but I have no interest in doing this myself.

Comment (thomaseizinger) [reply bitcoin-str/Cargo.toml:34]: > I'm unconvinced that "changes will happen" to hex encoding code which require synchronized updates, but concept ACK having a separate hex-compat crate.

That was my thinking as well. Very likely, the hex-encoding needs within `bitcoin-hashes` are not going to change any time soon and hence we might be able to reduce it down to 2-3 private functions that have exactly the signatures we need because the don't need to account for any other usage.

Contrary to that, a public `hex` module within `bitcoin-str` will likely need to offer much more flexible APIs, see more usage and thus require more maintenance.

That was the thinking when I proposed option 3 above. I am not fussed about extracting a dedicated crate though.

Comment (Kixunil) [reply bitcoin-str/Cargo.toml:34]: OK, I've mentioned there that I wish for MSRV to be no newer than 1.41.1 and noticed they also have 1.0 milestone which is very nice. I can see that the code being short and unlikely to change can be a good argument for duplication being fine but still prefer a separate crate. It could be a fork of `hex` with changes to make it compilable on 1.41.1.
