### PR TITLE
backport: Add support for pay to anchor outputs

### PR DESCRIPTION
**Pull request by tcharding**
Manually backport PR #4111. Of note, here we put `new_p2a` on `ScriptBuf` instead of on the `script::Builder` because that seems to be where all the other `new_foo` methods are in this release. 
    
From the original patch:

    Add support for the newly created Pay2Anchor output-type.
    
    See https://github.com/bitcoin/bitcoin/pull/30352

### CODE REVIEW

**Comment by apoelstra** [comment]
Does not compile with 1.56.1:

```
error[E0015]: calls in constant functions are limited to constant functions, tuple structs and tuple variants
   --> bitcoin/src/blockdata/script/witness_program.rs:108:64
    |
108 |         WitnessProgram { version: WitnessVersion::V1, program: ArrayVec::from_slice(&P2A_PROGRAM)}
    |                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0015`.
error: could not compile `bitcoin` due to previous error
```

**Comment by apoelstra** [comment]
Oh, it's specifically `cargo test --all-features --locked --doc` which fails, which is why CI didn't see it.

I would prefer we fix this because it will let me pass my local CI, though I don't really feel it's essential that our doctests meet MSRV.

**Comment by tcharding** [comment]
In `bitcoin` this now works for me locally: `cargo +1.51.1 test --all-features --locked --doc`

**Comment by apoelstra** [comment]
Oof, sorry for the long delay. But now I get

```
error: unexpected `cfg` condition name: `rust_v_1_61`
```

This is "just clippy" but it wasn't happening before and the fix is easy: just add `cfg(rust_v_1_61)` to the whitelist of cfg parameters in bitcoin/Cargo.toml.

**Comment by tcharding** [comment]
Added. No other changes.
