### PR TITLE
Add a FromStr-based serde deserializer

### PR DESCRIPTION
**Pull request by stevenroose**
Related to https://github.com/rust-bitcoin/rust-bitcoin/pull/501.

### CODE REVIEW

**Review by apoelstra — APPROVED** [review]

**Comment by apoelstra** [comment]
Doesn't compile with 1.29.0
```
cargo +1.29.0  build  '--no-default-features' '--features=rand use-serde base64' # cargo 1.29.0 (524a578d7 2018-08-05)
```
```
error[E0658]: access to extern crates through prelude is experimental (see issue #44660)
   --> src/util/amount.rs:938:27
    |
938 |         impl<'de, ValueT> serde::de::Visitor<'de> for Visitor<ValueT>
    |                           ^^^^^

error[E0658]: access to extern crates through prelude is experimental (see issue #44660)
   --> src/util/amount.rs:949:29
    |
949 |             fn visit_str<E: serde::de::Error>(self, v: &str) -> Result<Self::Value, E> {
    |                             ^^^^^

error[E0658]: access to extern crates through prelude is experimental (see issue #44660)
   --> src/util/amount.rs:953:38
    |
953 |             fn visit_borrowed_str<E: serde::de::Error>(self, v: &'de str) -> Result<Self::Value, E> {
    |                                      ^^^^^

error[E0658]: access to extern crates through prelude is experimental (see issue #44660)
   --> src/util/amount.rs:957:32
    |
957 |             fn visit_string<E: serde::de::Error>(self, v: String) -> Result<Self::Value, E> {
    |                                ^^^^^
```
etc

File: src/util/amount.rs [hunk 1]
```diff
@@ -1375,4 +1423,22 @@ mod tests {
...
+
+        #[derive(Deserialize, PartialEq, Debug)]
+        struct T {
+            #[serde(default, deserialize_with = "::util::amount::serde::parse")]
+            pub amt: Amount,
+            #[serde(default, deserialize_with = "::util::amount::serde::parse")]
+            pub samt: SignedAmount,
+        }
+
+        let t: T = serde_json::from_str("{\"amt\": \"2 BTC\", \"samt\": \"-5 sat\"}").unwrap();
```
Comment (dr-orlovsky) [inline src/util/amount.rs:1440]: JFYI, Nit: this can be done w/o quote escapes with raw string literals
```suggestion
        let t: T = serde_json::from_str(r#"{"amt": "2 BTC", "samt": "-5 sat"}"#).unwrap();
```

File: src/util/amount.rs [hunk 2]
```diff
@@ -914,12 +924,50 @@ pub mod serde {
...
+        D: Deserializer<'d>,
+        A: SerdeAmount,
+        <A as FromStr>::Err: ::std::fmt::Display,
+    {
+        use ::std::fmt::{self, Display, Formatter};
+        use ::std::marker::PhantomData;
+
+        struct Visitor<ValueT>(PhantomData<ValueT>);
+
+        impl<'de, ValueT> serde::de::Visitor<'de> for Visitor<ValueT>
```
Comment (dr-orlovsky) [inline src/util/amount.rs:938]: Fixes 1.29 compilation error
```suggestion
        impl<'de, ValueT> ::serde::de::Visitor<'de> for Visitor<ValueT>
```

File: src/util/amount.rs [hunk 3]
```diff
@@ -914,12 +924,50 @@ pub mod serde {
...
+            ValueT: FromStr,
+            <ValueT as FromStr>::Err: Display,
+        {
+            type Value = ValueT;
+
+            fn expecting(&self, formatter: &mut Formatter) -> fmt::Result {
+                formatter.write_str("a Bitcoin amount")
+            }
+
+            fn visit_str<E: serde::de::Error>(self, v: &str) -> Result<Self::Value, E> {
```
Comment (dr-orlovsky) [inline src/util/amount.rs:949]: Ibid
```suggestion
            fn visit_str<E: ::serde::de::Error>(self, v: &str) -> Result<Self::Value, E> {
```

File: src/util/amount.rs [hunk 4]
```diff
@@ -914,12 +924,50 @@ pub mod serde {
...
+                ValueT::from_str(v).map_err(E::custom)
+            }
+
+            fn visit_borrowed_str<E: serde::de::Error>(self, v: &'de str) -> Result<Self::Value, E> {
```
Comment (dr-orlovsky) [inline src/util/amount.rs:953]:
```suggestion
            fn visit_borrowed_str<E: ::serde::de::Error>(self, v: &'de str) -> Result<Self::Value, E> {
```

File: src/util/amount.rs [hunk 5]
```diff
@@ -914,12 +924,50 @@ pub mod serde {
...
+                self.visit_str(v)
+            }
+
+            fn visit_string<E: serde::de::Error>(self, v: String) -> Result<Self::Value, E> {
```
Comment (dr-orlovsky) [inline src/util/amount.rs:957]:
```suggestion
            fn visit_string<E: ::serde::de::Error>(self, v: String) -> Result<Self::Value, E> {
```

**Review by dr-orlovsky — CHANGES_REQUESTED** [review]
utACK, but with fixes for 1.29 compilation errors

**Comment by stevenroose** [comment]
Fixed those MSRV errors and rebased.

**Review by dr-orlovsky — APPROVED** [review]

File: src/util/amount.rs [hunk 6]
```diff
@@ -955,6 +965,45 @@ pub mod serde {
...
+
+        impl<'de, ValueT> de::Visitor<'de> for Visitor<ValueT>
+        where
+            ValueT: FromStr,
+            <ValueT as FromStr>::Err: Display,
+        {
+            type Value = ValueT;
+
+            fn expecting(&self, formatter: &mut Formatter) -> fmt::Result {
+                formatter.write_str("a Bitcoin amount")
```
Comment (sgeisler) [inline src/util/amount.rs:988]: Maybe note that it expects a denomination?

**Review by sgeisler — APPROVED** [review]
utACK dc54199c46169329500a27e43f8ac769ebfd172f

I think we should revisit the `FromStr` impl at some point and make it work properly (e.g. without spaces, like c-lightning would require it) at least if we still want to include and not deprecate it (I'm not sure if really that useful tbh, see my comment in #593).

File: src/util/amount.rs [hunk 7]
```diff
@@ -866,18 +866,28 @@ pub mod serde {
...
+
     use serde::{Deserialize, Deserializer, Serialize, Serializer};
     use util::amount::{Amount, Denomination, SignedAmount};
 
     /// This trait is used only to avoid code duplication and naming collisions
     /// of the different serde serialization crates.
     ///
     /// TODO: Add the private::Sealed bound in next breaking release
-    pub trait SerdeAmount: Copy + Sized {
+    pub trait SerdeAmount: Copy + Sized + FromStr {
```
Comment (apoelstra) [inline src/util/amount.rs:890]: Adding this bound is a breaking change, no?

Comment (dr-orlovsky) [reply src/util/amount.rs:890]: This trait is a "private" one and should not be used outside of the crate. However, this is not enforced (yet), so if somebody is using it against the recommendation, this may break their code.

File: src/util/amount.rs [hunk 8]
```diff
@@ -866,18 +866,28 @@ pub mod serde {
...
 
+    use std::str::FromStr;
+
     use serde::{Deserialize, Deserializer, Serialize, Serializer};
     use util::amount::{Amount, Denomination, SignedAmount};
 
     /// This trait is used only to avoid code duplication and naming collisions
     /// of the different serde serialization crates.
     ///
     /// TODO: Add the private::Sealed bound in next breaking release
```
Comment (dr-orlovsky) [inline src/util/amount.rs:889]: Probably we need here
```suggestion
    #[doc = hidden]
    // TODO: Add the private::Sealed bound in next breaking release
```

**Review by dr-orlovsky — CHANGES_REQUESTED** [review]
Needs rebase and replacement of all `std::` to `core::`

File: src/util/amount.rs (hunk 6 above)
Comment (stevenroose) [reply src/util/amount.rs]: done

File: src/util/amount.rs (hunk 8 above)
Comment (stevenroose) [reply src/util/amount.rs]: made it into a regular comment

**Comment by stevenroose** [comment]
Fixed and rebased.

**Review by dr-orlovsky — APPROVED** [review]
utACK

**Comment by tcharding** [comment]
For what its worth, I had a play around with this and it looks good to me.

**Comment by sanket1729** [comment]
Needs rebase. 

@stevenroose , we are gearing up for a major release soon. Otherwise, this might have to wait for 0.29

**Comment by tcharding** [comment]
Hey mate, this PR is currently marked as part of the 0.29 milestone, would you like to get this functionality in before the 0.29 release?

**Comment by tcharding** [comment]
No response from @stevenroose so I'm going to remove the milestone from this one.

**Comment by Kixunil** [comment]
This looks stale and I'd rather add `mod as_str`. We could have also `With<Strategy>` instead to handle different denominations but that seems too much.

Also is this actually needed in `bitcoincore-rpc` or anywhere else?

**Comment by Kixunil** [comment]
Closing as stale. Reopen when ready.
