### ISSUE TITLE
Cannot build no-std with Rust 1.36

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#782]
When trying to build with Rust 1.36 I ran into the following error for `no-std` feature. Note `no-std` builds fine with 1.41. I'm raising this issue in case this effects the upcoming discussion on bumping MSRV.

Or am I just braindead?
```
cargo +1.36 build --features=no-std
Compiling memchr v2.4.1
Compiling hashbrown v0.8.2
Compiling secp256k1 v0.21.2
error[E0658]: naming constants with `_` is unstable
--> /home/tobin/.cargo/registry/src/github.com-1ecc6299db9ec823/memchr-2.4.1/src/memmem/prefilter/fallback.rs:37:1
|
37 | const _: PrefilterFnTy = find;
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= note: for more information, see https://github.com/rust-lang/rust/issues/54912

error[E0658]: naming constants with `_` is unstable
--> /home/tobin/.cargo/registry/src/github.com-1ecc6299db9ec823/memchr-2.4.1/src/memmem/prefilter/x86/sse.rs:9:1
|
9 | const _: PrefilterFnTy = find;
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= note: for more information, see https://github.com/rust-lang/rust/issues/54912

error[E0658]: non exhaustive is an experimental feature
--> /home/tobin/.cargo/registry/src/github.com-1ecc6299db9ec823/memchr-2.4.1/src/memmem/prefilter/mod.rs:152:1
|
152 | #[non_exhaustive]
| ^^^^^^^^^^^^^^^^^
|
= note: for more information, see https://github.com/rust-lang/rust/issues/44109

error: aborting due to 3 previous errors

For more information about this error, try `rustc --explain E0658`.
error: Could not compile `memchr`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by Kixunil** [comment]
I think you need `cargo update -p memmem --precise some-older-version`

**Comment by thomaseizinger** [comment]
I don't think the msrv policy holds for no-std. AFAIK, we accepted that no-std would raise MSRV because for many embedded usecases, you often need nightly or at least a very recent rustc.

**Comment by Kixunil** [comment]
Actually, [`no_std` MSRV is supposed to be 1.47](https://github.com/rust-bitcoin/rust-bitcoin/pull/690#issuecomment-999929389)

@tcharding I suggest you try 1.47 and if it works close this.

**Comment by tcharding** [comment]
Oh I didn't realize about the MSRV thing for `no-std`. This works for 1.41 so closing.
