### PR TITLE
Add Network::to_core_arg() method

### PR DESCRIPTION
**Pull request by connormullett**
closes: #1207

Adds converting `Network` to its `bitcoind` equivalent.
The arguments for -chain can be found in the documentation and is one of the following:
main, test, signet, regtest

### CODE REVIEW

**Comment by apoelstra** [comment]
Thanks for your contribution!

```
error[E0277]: `[(&str, network::constants::Network); 4]` is not an iterator
   --> bitcoin/src/network/constants.rs:605:40
    |
605 |         for (expected_arg, network) in network_pairs {
    |                                        ^^^^^^^^^^^^^ borrow the array with `&` or call `.iter()` on it to iterate over it
    |
    = help: the trait `std::iter::Iterator` is not implemented for `[(&str, network::constants::Network); 4]`
    = note: arrays are not iterators, but slices like the following are: `&[1, 2, 3]`
    = note: required by `std::iter::IntoIterator::into_iter`
```
Oops, this won't compile with rustc 1.41, which is our MSRV. I think you just need to write `network_pairs.iter()` or something like that.

**Comment by connormullett** [comment]
Thanks for the info. When I get back to my desk I'll fix this up and verify it works locally at MSRV

**Comment by tcharding** [comment]
Thanks @connormullett, IMO we could just drop the unit test, the code is easy enough not to need it.

File: bitcoin/src/network/constants.rs [hunk 1]
```diff
@@ -104,6 +104,17 @@ impl Network {
     pub fn magic(self) -> Magic {
         Magic::from(self)
     }
+
+    /// Converts a `Network` to its equivalent bitcoind `-chain` option argument name.
+    /// Bitcoind documentation refers to the following allowed options: `-chain=[main, test, signet, regtest]`
```
Comment (tcharding) [inline bitcoin/src/network/constants.rs:109]: I went looking for how you found this and came up with these docs, use them if you like them :)
```suggestion
    /// Converts a `Network` to its equivalent `bitcoind -chain` argument name.
    ///
    /// ```bash,no_run
    /// $ bitcoin-23.0/bin/bitcoind --help | grep -C 3 '\-chain=<chain>'
    /// Chain selection options:
    ///
    /// -chain=<chain>
    /// Use the chain <chain> (default: main). Allowed values: main, test, signet, regtest
    /// ```
```

**Comment by connormullett** [comment]
> Thanks @connormullett, IMO we could just drop the unit test, the code is easy enough not to need it.

For sure, just trying to follow the contributing guidelines

File: bitcoin/src/network/constants.rs (hunk 1 above)
Comment (connormullett) [reply bitcoin/src/network/constants.rs:109]: Appreciate it! much cleaner than what I had going on haha

**Comment by tcharding** [comment]
> For sure, just trying to follow the contributing guidelines

Thanks for trying man! One more request, can you squash this down into a single commit please.

**Comment by connormullett** [comment]
> Thanks for trying man! One more request, can you squash this down into a single commit please.

Sure

**Comment by connormullett** [comment]
Might've messed something up trying to squash this. Never had to squash pre-merge. Normally I do it through github.

File: bitcoin/src/network/constants.rs [hunk 2]
```diff
@@ -582,6 +600,7 @@ mod tests {
         }
     }
 
+
```
Comment (apoelstra) [inline bitcoin/src/network/constants.rs:603]: Nit: you still added a newline here. (This is fine, I won't hold things up over it)

File: bitcoin/src/network/constants.rs [hunk 3]
```diff
@@ -104,6 +104,24 @@ impl Network {
     pub fn magic(self) -> Magic {
         Magic::from(self)
     }
+
+    /// Converts a `Network` to its equivalent `bitcoind -chain` argument name.
+    ///
+    /// ```bash,no_run
```
Comment (apoelstra) [inline bitcoin/src/network/constants.rs:110]: kek, if you hadn't specified `no_run` would rustdoc have tried to execute arbitrary bash code from a doccomment?

**Comment by apoelstra** [comment]
Looks like the squash worked, thanks! I am running my local tests and then will ack.

**Review by apoelstra — APPROVED** [review]
ACK 79cc855208ac47c7346ad80c480e11ea26fef137

File: bitcoin/src/network/constants.rs (hunk 3 above)
Comment (connormullett) [reply bitcoin/src/network/constants.rs:110]: I believe so lol, I don't think its a big security risk considering its ran locally but better safe than sorry. More so for copy/paste to verify where the options come from

File: bitcoin/src/network/constants.rs (hunk 2 above)
Comment (connormullett) [reply bitcoin/src/network/constants.rs:603]: Oops, if i were to go in and change this, would I have to re-squash and then get another approval? or would it be fine to merge with 2 commits

File: bitcoin/src/network/constants.rs (hunk 3 above)
Comment (tcharding) [reply bitcoin/src/network/constants.rs:110]: hah! That is my mistake. I'll fix in a follow up PR.

**Review by tcharding — DISMISSED** [review]
ACK 79cc855208ac47c7346ad80c480e11ea26fef137

**Comment by apoelstra** [comment]
@connormullett could you rebase this on the current master? It looks like the recent merge of #1353 has caused a conflict.

**Comment by connormullett** [comment]
Resolved conflicts and rebased

**Comment by connormullett** [comment]
Remove newline from between tests

**Review by apoelstra — APPROVED** [review]
ACK 519db4d9515d11f3f7243d1ea10c0fefc700ece4

File: bitcoin/src/network/constants.rs (hunk 3 above)
Comment (Kixunil) [reply bitcoin/src/network/constants.rs:107]: I believe rustdoc doesn't understand anything else than `rust` so `bash` has no effect and without `no_run` it'd try to compile it as Rust code.

**Review by Kixunil — APPROVED** [review]
ACK 519db4d9515d11f3f7243d1ea10c0fefc700ece4

FTR I checked and `no_run` is not really needed for `bash`. It still doesn't have highlighting for bash but I suggest we keep it in case a future version does.

File: bitcoin/src/network/constants.rs (hunk 3 above)
Comment (tcharding) [reply bitcoin/src/network/constants.rs:107]: I had a hunch that it just defaulted to `///rust` and if anything else was there it meant no default so not rust - hence it would not be run. And after trying it out, yes building the docs with no marker gives
```
    = note: error from rustc: unknown character escape: `-`
    = note: `#[warn(rustdoc::invalid_rust_codeblocks)]` on by default
help: mark blocks that do not contain Rust code as text
    |
107 |     /// ```text
    |            ++++
```
and running `cargo test --doc` fails. Appending any of `bash`, `no_run`, or `aoseunthao` clears the warning and stops the code being run and the tests all pass.

Comment (tcharding) [reply bitcoin/src/network/constants.rs:107]: When I added `bash` I had hoped that `bash` would give us syntax highlighting in the html docs but it does not. Bad Tobin for not checking originally.

Comment (Kixunil) [reply bitcoin/src/network/constants.rs:107]: I'd still keep adding correct language names. You never know when they add the support. :)

Comment (Kixunil) [reply bitcoin/src/network/constants.rs:107]: FYI: this was already requested: https://github.com/rust-lang/rust/issues/43165

**Comment by tcharding** [comment]
> FTR I checked and no_run is not really needed for bash. It still doesn't have highlighting for bash but I suggest we keep it in case a future version does.

I really should scroll all the way through comments before posting, had not read this one when I wrote mine, not that it matters.

File: bitcoin/src/network/constants.rs (hunk 3 above)
Comment (tcharding) [reply bitcoin/src/network/constants.rs:107]: Yeah I suppose so, especially since we build docs with nightly.
